### ISSUE TITLE
GlobalRef should be Send + Sync?

### ISSUE THREAD

**Issue by mmastrac** [jni-rs/jni-rs#102]
I'm dealing with a case where I need to hold a struct containing a `GlobalRef` inside of an `Arc<...>` and it's not happy with the fact that `GlobalRef` isn't `Sync`.

My understanding is that GlobalRef is both thread-agnostic and thread-safe [1], so it should be safe to make it `Sync` as well. 

[1] http://www.latkin.org/blog/2016/02/01/jni-object-lifetimes-quick-reference/

**Comment by dmitry-timofeev** [comment]
Definitely, `GlobalRef`s are thread-safe, and there is already a workaround to access the same underlying global reference (C-JNI) from different threads by cloning it, if I understand correctly. @alexander-irbis , do you remember if there is any reason against making it `Sync`?

**Comment by skletsun** [comment]
The definition of `Sync` from its source file:

> The precise definition is: a type `T` is `Sync` if and only if `&T` is `Send`. In other words, if there is no possibility of undefined behavior (including data races) when passing `&T` references between threads.

The methods of `GlobalRef` provide correct references to correct entities between threads and provide no interior mutability in a non-thread-safe form. With regards to this, I believe that it is safe for `GlobalRef` to implement the `Sync` trait as well.
