### ISSUE TITLE
Inconsistency in Desc<JClass> implementations for reference types

### ISSUE THREAD

**Issue by dmitry-timofeev** [jni-rs/jni-rs#118]
## Overview
Desc<JClass> implementation for `JObject` returns the object class instead of casting the object to JClass; implementations for `GlobalRef` and `AutoLocal` cast to JClass.

Since `Desc#lookup` happens implicitly for the user code, inconsistency here does not seem acceptable. Furthermore, such implementation for `JObject` allows the code:
```rust
env.call_static_method(foo_ref, "bar", "()I", &[]);
```
which might fail depending on the runtime type of `foo_ref`.

## Questions
1. [ ] Shall we allow casting reference objects (JObject, AutoLocal, GlobalRef) to JClass _through_ `Desc#lookup` (or require explicit `.into()`)?

**Comment by rib** [comment]
hmmm, this is quite a surprising inconsistency actually!

If an API expects a class and gets passed a local reference (in the form of a `JObject`) then we should surely assume its a reference to a class. It seems odd that you can actually pass a kind of example instance and have that be interpreted as a class.

**Comment by argv-minus-one** [comment]
This does mirror Java, where you can call a `static` method on an object reference, even if the object reference's class is a subclass of the class that actually defines the `static` method.

That doesn't mean *we* have to allow it, of course. Just pointing out that there is some precedent for this behavior.

**Comment by rib** [comment]
yeah but isn't that just a special privilege for the compiler which does that to make the language itself convenient / ergonomic?  

Presumably that syntactic convenience that lets you call static methods with an instance is resolved / normalized / lowered at compile time into the equivalent of `MyClass.staticMethod()`

although that automatic fallback logic is convenient for making static method calls in Java itself I'm not sure that same kind of fallback is what you'd want in all APIs that accept a class reference.

e.g. skimming `jnienv.rs` I see these apis expect a class reference: `new_object`, `new_object_array`, `register_native_methods`, `get_superclass` and `is_assignable_from`

the idea of passing an instance to `new_object` seems quite odd to me at least; I think it seems odd to me for all of these.
