### ISSUE TITLE
Consider unchecked exception as the default for Desc<JThrowable>

### ISSUE THREAD

**Issue by dmitry-timofeev** [jni-rs/jni-rs#119]
## Overview
Checked `j.l.Exception` is used as the default in `Desc<JThrowable>` implementations. Such exception cannot be thrown unless the Java native method declares it.

`j.l.RuntimeException` might be more appropriate, on the other hand, it might be reasonable to always require the callers to specify the exception type explicitly.

## Questions
1. [ ] Shall we allow to create an exception of a default type (e.g., `j.l.RuntimeException`) or always require to specify its type?

**Comment by skletsun** [comment]
>     1. [ ]  Shall we allow to create an exception of a default type (e.g., `j.l.RuntimeException`) or always require to specify its type?

I'd suggest creating an exception of `j.l.RuntimeException` type by default for the sake of simplicity -  we already have an ability to specify exact exception type if required.
