### ISSUE TITLE
Ensure proper Windows/Mac support for Invocation API

### ISSUE THREAD

**Issue by dmitry-timofeev** [jni-rs/jni-rs#144]
Some things that might need to be improved:
* Load a `.dll` instead of `.so`
* Use proper path delimeters (`:` on Linux/Mac and `;` on Windows)
* Fix the algorithm searching for required JVM libraries:
  * [Apparently](https://github.com/jni-rs/jni-rs/pull/143#discussion_r222700472), `jvm.lib` is required on top/instead of `jvm.dll`. It might be that the latter is required only at runtime, see https://stackoverflow.com/a/2337985/1792188
  * Consider taking JAVA_HOME from the java output if JAVA_HOME is not set (see below).

### Possible search algorithm
1. Find libjvm in either:
    1. JAVA_HOME
    1. (if it is not set): `java.home` extracted from `java -showProperties …` output.

**Comment by dmitry-timofeev** [comment]
I'd research when and how one have to link these libraries and what the effects are:

1. Is `jvm.lib` is a so-called "import library" that, when linked, loads `jvm.dll` automatically?
1. If we do link `jvm.lib` statically would it automatically load `jvm.dll` from a _hard-coded_ (= compile-time-defined) path?
1. Is it *required* to link `jvm.lib`?
    1. Can we load a `jvm.dll` manually  in an application or from `PATH` if we do **not** link `jvm.lib` statically?
1. Is `jvm.dll` required during building?

@DarkEld3r as someone who has experience building apps on Windows, do you know the answers to any of these?

**Comment by DarkEld3r** [comment]
@dmitry-timofeev 
I do have some experience with Windows, but that is in the past and wasn't related to Java. :upside_down_face: 
Unfortunately, I don't know the answers.

**Comment by repolevedavaj** [comment]
Maybe I can help with number 3: Currently it is required to link the library because the 'jni-sys' crate references these external functions:
```
extern "system" {
    pub fn JNI_GetDefaultJavaVMInitArgs(args: *mut c_void) -> jint;
    pub fn JNI_CreateJavaVM(
        pvm: *mut *mut JavaVM,
        penv: *mut *mut c_void,
        args: *mut c_void,
    ) -> jint;
    pub fn JNI_GetCreatedJavaVMs(vmBuf: *mut *mut JavaVM, bufLen: jsize, nVMs: *mut jsize) -> jint;
}
```
Because of these references, you must link a library while compiling, which provides the implementation of these. 

If you do not want to link a library while compiling, you must remove these references and load the desired function of a library on runtime:

```
// load library with 'libloading' crate dynamically
let lib = lib::Library::new("../jre/lib/server/libjvm.dylib").unwrap();

// get function from library
let JNI_CreateJavaVM: lib::Symbol<unsafe extern fn(
    pvm: *mut *mut JavaVM,
    penv: *mut *mut c_void,
    args: *mut c_void,
) -> jint> = lib.get(b"JNI_CreateJavaVM").unwrap();

// call function as usual
jni_error_code_to_result(JNI_CreateJavaVM(
    &mut ptr as *mut _,
    &mut env as *mut *mut sys::JNIEnv as *mut *mut c_void,
    args.inner_ptr(),
))?;
```

**Comment by dmitry-timofeev** [comment]
Hi @repolevedavaj , 

I think it might be a useful feature, but there are a couple of questions:

1. Does such a feature conflict with the present way of dynamic linking a JVM library (at start-up time)?

2. Can this library provide both ways of loading the libjvm library?

3. Can it be (relatively easy) implemented in a cross-platform way?

**Comment by dmitry-timofeev** [comment]
Closing as Invocation API works fine on Windows.
