### ISSUE TITLE
Improve JNIEnv#get_superclass()

### ISSUE THREAD

**Issue by skletsun** [jni-rs/jni-rs#151]
The current implementation of JNIEnv#get_superclass() uses jni_non_null_call!() for GetSuperclass which is a little redundant since GetSuperclass does not throw any exception thus jni_unchecked!() could be used. But it may return NULL for an object/interface that doesn't have a superclass. The suggested behavior for this case is to still treat this as an error but probably it worth introducing another entity like Err(NoSuperClass("<class/interface name> can't have a super class")) instead of the NullPtr.

**Comment by marschall** [comment]
What about returning Option None instead?

**Comment by TheDutchMC** [comment]
> What about returning Option None instead?
This would make the most sense I'd think. Since not having a superclass isn't really an error. Option<T> where null translates to None would be most appropriate I'd say
