### ISSUE TITLE
Panic handlers

### ISSUE THREAD

**Issue by marschall** [jni-rs/jni-rs#154]
I don't know how to get in touch with the project (gitter has some issues with my Safari) so I open an issue for this.

I wonder whether it makes sense in general to wrap JNI code with a panic handler that throws a Java exception on a panic.

```rust
#[no_mangle]
#[allow(non_snake_case)]
pub extern "system" fn Java_HelloWorld_hello(env: JNIEnv,
                                             _class: JClass,
                                             input: JString)
                                             -> jstring {
    let result = panic::catch_unwind(|| {
        say_hello(&env, &input)
    });

    match result {
        Ok(s) => s,
        Err(cause) => {
            if let Some(cause) = cause.downcast_ref::<&str>() {
                env.throw_new("java/lang/RuntimeException", cause);
            } else {
                env.throw_new("java/lang/RuntimeException", "panic occurred");
            }
            (::std::ptr::null_mut() as jstring)
        }
    }
}

fn say_hello(env: &JNIEnv, input: &JString) -> jstring {
    let input: String = env.get_string(*input)
        .expect("Couldn't get java string!").into();
    let output = env.new_string(format!("Hello, {}!", input))
        .expect("Couldn't create java string!");
    return output.into_inner();
}
```

Does this make any sense? I do ignore the return value of `throw_new` here, I could do `fatal_error` instead. Would it make sense do document this? Could this be done somewhat nicer, eg. with a macro?

**Comment by dmitry-timofeev** [comment]
Issue is good :wink: ,
AFAIK, it is a good practice to catch panics at JNI boundaries. In Exonum Java Binding we have extracted that last bit in a method that also detects Java exceptions thrown in native code:

https://github.com/exonum/exonum-java-binding/blob/b4f2dba304add4bab68f2c5b5b5364ff4e28adab/exonum-java-binding-core/rust/src/utils/exception.rs#L26-L49

I thought the docs or example mentioned that, but could not find it. It would be good to improve them.

Regarding your other questions — I think someone more experienced with Rust would be able to answer them :-)

**Comment by alexander-irbis** [comment]
@marschall 
```rust
    match result {
        Ok(s) => s,
        Err(cause) => {
            if let Some(cause) = cause.downcast_ref::<&str>() {
                env.throw_new("java/lang/RuntimeException", cause);
            } else {
                env.throw_new("java/lang/RuntimeException", "panic occurred");
            }
            (::std::ptr::null_mut() as jstring)
        }
    }
```
This code can be slightly simplified:
```rust
    result.unwrap_or_else(|cause| {
        env.throw_new("java/lang/RuntimeException",
                                 cause.downcast_ref::<&str>().unwrap_or("panic occurred"));
        JObject::null().into_inner()
    })
```
But you are right, it’s worth doing something to reduce the boilerplate.

**Comment by dmitry-timofeev** [comment]
Closing, if there are any suggestions to improve the amount of boilerplate, please reopen or submit a new issue.

**Comment by cherryleafroad** [comment]
Just want to throw this in here for Googlers.

It's best to always wrap everything in a `std::panic::catch_unwind` for jni calls, since that's pretty much the exact purpose for it. Stop unwinding from panics so they don't unwind into ffi. Additionally, you can display the panic error to the user if there is a panic through a normal match.

Of course, you can use result types like normal for your functions; just remember that a result type WON'T stop a panic, which is why this function is basically needed.
