### ISSUE TITLE
Support for weak globals refs

### ISSUE THREAD

**Issue by emilsjolander** [jni-rs/jni-rs#167]
This library is awesome! Using it to add Android support for https://github.com/vislyhq/stretch :) One thing that I found missing was the ability to create weak references (NewWeakGlobalRef & DeleteWeakGlobalRef JNI functions, see https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html)

Is there any reason I should know about as to why these have not been implemented? I'm happy to give a go at implementing this. I would probably try to start by basically copy-pasting all the GlobalRef code and prefixing it with 'Weak', and ensuring to call the correct underlying JNI code. Does that sounds about right?

**Comment by vitvakatu** [comment]
I think the main reason weak references weren't added to the library is that they are extremely unsafe and may turn in NULL at any moment. If you're missing this funcitonality - go ahead, feel free to ask if you face any difficulties during implementation.

**Comment by emilsjolander** [comment]
Ok good to know! I'll first see if I can work around it by moving the weak ref to the JVM side instead. But otherwise i'll give it a go.

**Comment by dmitry-timofeev** [comment]
> they are extremely unsafe and may turn in NULL at any moment.

They seem to be about as unsafe as usual WeakReferences: you first need to turn them into a strong one ("get" them), _then_ check for `null`, and finally you can use it. But please note they are not the same: JNI WeakGlobalRefs are said to be "weaker", meaning they are not "cleared", or become inaccessible, until WeakReferences and SoftReferences are cleared.

In java, that's

```
WeakReference<T> weakFoo;
T foo = weekFoo.get(); // turn into strong, 
if (foo != null) { // check it hasn't been cleared — points to a non-null object
  use(foo); // finally, use
}
```

In JNI that's the same pattern:

```
WeakGlobalRef week_foo;
AutoLocal foo = env.new_local_ref(week_foo); // turn into strong
if (!env.is_same_object(foo, null)) { // check it hasn't been cleared — points to a non-null object
  use(env, foo);
}
```

**Comment by dmitry-timofeev** [comment]
I think it wasn't implemented earlier just because of lack of demand for this feature :-) 

One thing regarding the implementation: given its nature and drastic difference from GlobalRef (can turn into `null` at _any_ time), it must not be allowed to cast it (as `GlobalRef#as_obj` does) to `JObject`, because such cast won't turn it into a strong reference, it will just create a new Rust wrapper around same JNI WeakGlobalRef.
