### ISSUE TITLE
Detach threads automatically on exit

### ISSUE THREAD

**Issue by dmitry-timofeev** [jni-rs/jni-rs#179]
Detach attached through Invocation API threads automatically on their exit.

In the present version:
 - The daemon threads cannot be detached (see #128), potentially, leaking VM memory; 
 - Regular threads are detached as soon as the `AttachGuard` returned by `JavaVM#attach_current_thread` is dropped, which, albeit a leak-safe option, might not be the desired behaviour if the same native thread needs to repeatedly and frequently call into Java, because of high overhead of attach/detach operation;
- There is no reliable **and** efficient way of managing attachment of 'foreign' native threads — the one your app does not control.

The goal of this issue is to provide a mechanism to attach the native threads 'permanently' — till they exit; and automatically detach them on exit. That can be achieved utilising thread-local storage, by placing there a guard object similar to `AttachGuard`.

There is a recommendation to use such approach with examples using pthreads in [Android tips](https://developer.android.com/training/articles/perf-jni#threads_1) and on [SO](https://stackoverflow.com/a/30026231/1792188).

There are some questions on the API:
1. What is the default for `attach_current_thread`: attach locally, or permanently?
2. Shall we support both modes for `attach…_as_daemon`, or only permanently?
3. Shall we also take care of the local frame (as a user failure to manage locals properly is likely to be more severe than with briefly attached threads), for instance, with such interface: 
```rust
vm->with_attached_as_daemon(|env| -> { 
  /* Use env, the local frame has already been allocated */
});
// That, however, still leaves some potential for misuse:
let env = vm->get_env()?;
// Yay, let's leak some locals, forgetting of frames/auto_locals
while true {
  env.new_object()?;
}
```
or leave it for an abstraction atop JavaVM (e.g., an `Executor` as in #83 )?

**Comment by vitvakatu** [comment]
Implementation in #180 answers the above questions the following way:
1. `attach_current_thread` preserves old behaviour, thread is attached until returned `AttachGuard` dropped.
2. `attach_current_thread_as_daemon` attaches the thread permanently, no other option provided
3. Local frames handling is not implemented

The following questions arose: 
1. Should we detach the thread in `JavaVM::new`? Current implementation does it, though original JNI implementation doesn't.
2. `detach_current_thread` immediately detaches current thread, breaking any existing `AttachGuard`s. It's obviously not safe for user, especially in case of nested attaches in a large code bases. Should we remove this method completely or just make it unsafe and thoroughly document it? Are there any usage cases for such method? Should we try to improve current implementation and preserve existing `AttachGuard`s?

**Comment by dmitry-timofeev** [comment]
> Should we detach the thread in JavaVM::new? Current implementation does it, though original JNI implementation doesn't.

That's a good question. The original JNI API gives users full control over that — attaching the current thread on VM instantiation, it provides `DetachCurrentThread` to detach it immediately or later at any point. The JNIEnv is accessed through `GetEnv`.

Therefore, if we do keep the thread attached, we must also provide an opportunity to access the JNIEnv and to detach the thread. 

I see the following options:
1. Similar to C JNI, JNIEnv can be accessed with `get_env`. Thread can be detached  with `detach_current_thread`. That leaves some possibility of errors (using env *after* detach), and also will make any explicit `JavaVM#attach_x` no-ops.
2. `JavaVM#new` returns a tuple (JavaVM, JNIEnv). JNIEnv is immediately accessible through AttachGuard. Thread will be detached once the guard is dropped. Explicit `JavaVM#attach_x` are still no-ops till you drop the guard — but at least you hold it in a variable (and see it's there). There might be variations, like providing `JavaVM#new -> (JavaVM, JNIEnv)` and `JavaVM#new_detached -> (JavaVM)`.
3. The current state: `JavaVM#new` detaches the thread. JNIEnv can be obtained through any `JavaVM#attach_x`, which employ different policies on detachment.

Which is safer, more convenient, and less surprising to use? How do these options work when VM is put in a global variable?

> detach_current_thread

Not sure about use-cases, but maybe detach the thread that was attached permanently because the attachment scope is rather large and loosely-defined and someone don't want to use AttachGuard? 

We can remove it till a realistic use-case arises where scoped and permanent attaches are not enough.

**Comment by vitvakatu** [comment]
After some consideration, I decided to mark `detach_current_thread` method as hidden. It will allow us to use it if needed, and also makes "stabilization" of this method super-easy, as we do not loose existing code and tests.

Option 2 (returning guard from `JavaVM::new`) complicates any code, as the user will need to handle this guard, involves some complications of usage of statics (You will need to store not only JavaVM, but also a guard together and somehow guarantee, that guard will not live more than VM).

Option 1 seems good enough, but it **needs** `detach_current_thread`, as it would be impossible to detach thread otherwise. 

So current option (3) doesn't need `detach_current_thread`, though we can take some advantage of still keeping this method in the API as a backdoor for some exceptional situations.

Current workflow, when you need to use `attach_*` seems less surprising, making thread management more explicit.

I also thought about making `detach_current_thread` unsafe, but not sure yet.

**Comment by dmitry-timofeev** [comment]
OK, although option 3 has an inconsistency with the JNI API (it keeps the thread attached), we can prefer it to O2 (guard from `JavaVM::new`) because it’s simpler to use. O1, though behaves the same as the JNI API, does not work well with anything else.

If that's correct, I'd consider extending the documentation on
- `JavaVM::new` to note that unlike JNI counter-part, the thread remains detached and can be attached using any `attach_…` methods (link to apr. section).
- `detach_current_thread` to note that it is _never_ appropriate to use for scoped attaches; and might rarely be for permanent attaches.

**Comment by dmitry-timofeev** [comment]
> It will allow us to use it if needed

Won't it allow _anyone_ who finds it?

**Comment by DarkEld3r** [comment]
> Won't it allow anyone who finds it?

Yes, it is. There is one more option: hide this method under feature, which will make accidental use less likely, but this probably needlessly complicates code.
It would be convenient to use `#[unstable] ` attribute, but as far as I know it is still [unavailable](https://github.com/rust-lang/rfcs/issues/1491).

**Comment by vitvakatu** [comment]
> hide this method under feature

Yep, it will complicate tests

**Comment by dmitry-timofeev** [comment]
I agree that the complication with feature is unnecessary. Probably, hidden + some **bold** would be enough :upside_down_face: Or CAPS, in the extreme case :-)
