### ISSUE TITLE
Unsound conversion methods from jni_sys::jobject to jni::JObject and other wrappers

### ISSUE THREAD

**Issue by MaulingMonkey** [jni-rs/jni-rs#197]
`jni_sys::jobject` and friends are simply raw pointers, whereas `jni::JObject` is generally assumed to be a valid object.  This causes soundness problems if there are safe conversion methods from the former to the latter - this crashes in an access violation without any `unsafe`:
```rust
use jni_sys;
use jni;

fn main() {
    let args = jni::InitArgsBuilder::new().version(jni::JNIVersion::V8).build().unwrap();
    let vm = jni::JavaVM::new(args).unwrap();
    let env = vm.attach_current_thread().unwrap();
    let bad_object = jni::objects::JObject::from(42 as jni_sys::jobject);
    let hash_code = env.call_method(bad_object, "hashCode", "()I", &[]).unwrap().i().unwrap();
    println!("Hello, world!  bad_object.hashCode(): {}", hash_code);
}
```

Thanks to conversion methods like this: https://github.com/jni-rs/jni-rs/blob/3ad3c9db5d74e1c693e4f523ceb7654d3defad7d/src/wrapper/objects/jobject.rs#L20-L27

I'd recommend replacing these with unsafe fns ala `JavaVM::from_raw`... which unfortunately will be a breaking change.

**Comment by DarkEld3r** [comment]
Thanks for the observations. It is definitely a soundness issue.
