### ISSUE TITLE
Implement `From<JString>` for `JValue`

### ISSUE THREAD

**Issue by jvff** [jni-rs/jni-rs#205]
There is currently no way to convert a `JString` to a `JValue` using `my_jstring.into()`. It would be interesting to have an automatic `impl<'a> From<JString<'a>> for JValue<'a>`, but I'm not sure if it would be better to make it more generic, with something like `impl<'a, T: Into<JObject<'a>>> From<T> for JValue<'a>`. The restriction

I can open a PR to implement this extension, but I'm not sure what would be the best option.

**Comment by dmitry-timofeev** [comment]
Do I understand correctly that you consider extending the present `From` implementations, including [`From<JObject>`](https://github.com/jni-rs/jni-rs/blob/master/src/wrapper/objects/jvalue.rs#L169-L173), to accommodate some other possible JObjects, including JString?

There are, actually, quite some things that are, essentially, a JObject (simple wrappers, like JString, JClass, ..., JThrowable; and some special cases: AutoLocal and GlobalRef). Would it be possible to make JValue compatible with all or most of them without explicit From implementation for each of the types?

**Comment by dmitry-timofeev** [comment]
@vitvakatu , @skletsun This not-yet exported issue might be related (internal): https://jira.bf.local/browse/ECR-1067

**Comment by vitvakatu** [comment]
I see several options here:
1) The most straightforward one, implement `From<?> for JValue` for every type for which such conversion would be possible. Definitely not the best idea.
2) Suggestion of @jvff: implement `From<T: impl Into<JObject>> for JValue`. It allows to replace two conversions (T -> JObject -> JValue) with only one (T -> JValue).
3) Combination of ECR-1067 and @jvff 's idea. Implement `AsObj` trait for each type for which such operation is possible, and then implement `From<T: impl AsObj> for JValue`. In addition to less conversions when using `JValue`, it also allows to avoid `.into()` calls for other functions that accept `JObject`s (by changing their signature from `some_func(JObject)` to `some_func(impl AsObj)`.

**Comment by skletsun** [comment]
Implemented the third suggested option in the #206.

**Comment by dmitry-timofeev** [comment]
Good, currently for a wrapper type `W` there are:

1. From<W> for JObject
2. Deref for W, target = JObject (except AutoLocal & GlobalRef — why?)
3. AsObj for W

Would you please clarify the place of the various traits that the wrappers around JObject implement? Does each of them cover a distinct use-case or is there an overlap?

**Comment by dmitry-timofeev** [comment]
Regarding the question in the PR on whether AsObj shall be present in APIs, isn't the main value of AsObj trait in allowing a method that needs JObject (_any_ object, i.e., a JObject in the API does not imply any particular type that is behind that reference) to accept any wrapper type?

**Comment by skletsun** [comment]
1) `From` is for conversion (can be costly) that consumes the original object. Could be implicitly called by compiler in some specific cases (like error handling with the `?` operator).
2) `Deref` allows convenient access to data behind smart pointers. Implicitly called on arguments of functions and methods. If `T` implements `Deref<Target = U>`, and `x` is a value of type `T`, then values of type `&T` are coerced to values of type `&U` and `T` implicitly implements all the (immutable) methods of the type `U`.
3) `AsObj` does cheap "conversion" between JObject wrappers (by exposing internal value) and allows passing any wrappers arguments to the methods that require `JObject`.

The `From` solves mentioned problem if we're not interested in the original object. `Deref` is great when there are methods that accepts wrapper objects by reference. For the moment, the majority of the `JNIEnv` methods, for example, are accepting regular `JObject` and we have to use `*obj` to go with implicit `Deref` coersion.

**Comment by dmitry-timofeev** [comment]
> For the moment, the majority of the JNIEnv methods, for example, are accepting regular JObject

If we consider changing the signatures to accept `AsObj`, shan't we also equally consider changing them to accept a reference to `JObject` instead? I.e., if `&JObject` is accepted, would `Deref` solve the issue instead of `AsObj`? Or will `AsObj` also have value?

**Comment by skletsun** [comment]
There is still discussion in progress about the reasonability of the `AsObj` trait, thus better to separate this issue from it. Reverted corresponding changes from #206, improved conversion from the object wrappers to `JValue`.

**Comment by dmitry-timofeev** [comment]
Must be in v0.15.0.
