### ISSUE TITLE
Local reference leak on class lookups

### ISSUE THREAD

**Issue by jvff** [jni-rs/jni-rs#208]
`impl<'a, T> Desc<'a, JClass<'a>> for T where T: Into<JNIString>` uses `JNIEnv::find_class` to perform the lookup. However, the returned object (a local reference) is never released. This means many calls to `find_class` can cause the local reference buffer to overflow.

I'm not sure what would be the solution to such a problem. One (perhaps rather complex) proposal would be to have `trait Desc` contain an associated type `type LookUpResult: Deref<T>`, so that it can return something that's not a `JClass` but can in theory be used as one. Then, the `LookUpResult` would have to be some sort of smart-pointer, like `AutoLocal`. Either an `AutoLocalJClass` is needed, or `AutoLocal` could be extended to have a type parameter (that by default would be `JObject<'a>`).

Another potential solution is to have `JNIEnv` contain some sort of "class cache", where the class references are stored as `GlobalRef`s, but I'm not sure if this would be too much out of scope.

**Comment by dmitry-timofeev** [comment]
Hi, thanks for the report! Do I understand correctly that's the same problem described in #109? 

It's absolutely correct that such implicit lookups shall not leak local references. I think your first suggested solution where lookup returns an object that knows whether or not a new local reference has been created during the lookup and if it shall be deleted afterwards, would work. It seems to be similar to the solution 3b documented in #109. There is also 3a with a little smaller complexity but a runtime penalty when lookups are not needed.

Regarding the class cache — it is interesting to consider, but I think it would be extremely hard to make it work in 100% of cases in which the library could be used (e.g., classloaders that could be unloaded).

Even though the lookups must not leak, such leaks are often a manifestation of a problem in user code (e.g., repeated lookups by descriptor in a loop, leading to poor performance; or a failure to manage local references in manually-attached threads using [`Executor`/`with_local_frame`](https://docs.rs/jni/0.13.1/jni/struct.JavaVM.html#local-reference-management)).

**Comment by jvff** [comment]
Thanks for the info! And sorry for not finding the initial issue report :sweat_smile: Should I close this issue?

**Comment by dmitry-timofeev** [comment]
No worries :) Yes, let's keep the discussion in that issue.
