### ISSUE TITLE
Add jar packing feature

### ISSUE THREAD

**Issue by Tolsi** [jni-rs/jni-rs#215]
I made a JNI interface for my Rust code and now I don’t know how to make a jar file from this to add to my project. It would be convenient if there was an instruction for that or a command for packing it all in a jar package.

**Comment by dmitry-timofeev** [comment]
I think it is a question of packaging and distribution of your code which is out of scope for this library. Various solutions might make sense depending on the type of code (a Java library or an application), cross-platform support requirements (shall a lib/app depending on a native library work on a single platform or multiple), application security considerations, any other distribution requirements/restrictions.

For some libraries it might be sensible to make platform-specific libraries, publish them with different [classifiers](https://maven.apache.org/pom.html#Dependencies), and require dependent projects to pick a correct one using a classifier (and a type, if needed). That's how protoc is published to Maven and consumed by dependencies, for instance: https://github.com/exonum/exonum-java-binding/blob/99639c1ca73d4ae84dfef03a8dd6d84c5d0c873a/exonum-java-binding/common/pom.xml#L149

For other libraries it might be sensible to include native libraries for all supported platforms and architectures in the JAR resources and load from there (but it might be tricky to get right and secure, and inflates the JAR size).

For some apps it might be reasonable to distribute a native library and JAR separately, and configure the app with its installation location.

Surely, the options are not exhaustive, and there might be other solutions suitable to your project.

**Comment by Tolsi** [comment]
Okay, got it. I also have a question: how can I bind my code to class in a package? there're an example for a class without a package.

**Comment by dmitry-timofeev** [comment]
Name accordingly: https://docs.oracle.com/en/java/javase/11/docs/specs/jni/design.html#resolving-native-method-names 

You may tell javac to generate a C header file with correct names by passing `-h <output_dir>` option:

https://github.com/exonum/exonum-java-binding/blob/99639c1ca73d4ae84dfef03a8dd6d84c5d0c873a/exonum-java-binding/core/pom.xml#L197-L198

**Comment by Tolsi** [comment]
Thanks!
