### ISSUE TITLE
Derive `Clone` and maybe `Copy` for `JavaVM`

### ISSUE THREAD

**Issue by jvff** [jni-rs/jni-rs#217]
Would it make sense to have `Clone` and maybe also `Copy` derived for `JavaVM`?

**Comment by vitvakatu** [comment]
You can always use [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html) to make `JavaVM` clonable. It is the prefered way. `Copy` does make sense for primitive types only, so it is not suitable here.

**Comment by jvff** [comment]
Great! Thanks for the quick answer :)
