### ISSUE TITLE
Expose SetStatic*Field APIs

### ISSUE THREAD

**Issue by luser** [jni-rs/jni-rs#226]
It looks like this crate exposes the `GetStatic*Field` APIs:
https://docs.rs/jni/0.14.0/jni/struct.JNIEnv.html#method.get_static_field

but not the corresponding `SetStatic*Field` APIs:
https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#wp20829

It would be nice to support those as well.

**Comment by dmitry-timofeev** [comment]
Makes perfect sense.
