### ISSUE TITLE
“No Java runtime present, requesting install.” message on MacOS High Sierra

### ISSUE THREAD

**Issue by tiepettersen** [jni-rs/jni-rs#229]
On MacOS High Sierra I'm seeing the dialog “No Java runtime present, requesting install.” when my rust executable is calling the JavaVM invocation API, and subsequently immediately terminates. I've also made sure both `JAVA_HOME` and `LD_LIBRARY_PATH` are set correctly to the installed JDK on the MacOS machine. 

I'm using JDK version 1.8.0. 

After doing some searching, it seems like I'm not the only one experiencing this issue.
- https://github.com/xamarin/java.interop/pull/198
- https://github.com/JuliaInterop/JavaCall.jl/issues/100 
- https://github.com/kivy/pyjnius/pull/441
- https://github.com/imagej/pyimagej/issues/10

It seems like the workaround to the issue is to link to `libjli.dylib` instead of `libjvm.dylib` on MacOS. 

I've locally modified `build.rs` to test this out, and can confirm that this workaround does fix the issue.

**Comment by vitvakatu** [comment]
Hello, @tiepettersen 
Thank you for creating an issue!

Do you want to submit a PR with a fix?

Duplicated: https://github.com/jni-rs/jni-rs/issues/220

**Comment by tiepettersen** [comment]
@vitvakatu sure, I'll submit a PR.

**Comment by dmitry-timofeev** [comment]
Released in https://crates.io/crates/jni/0.16.0
