### ISSUE TITLE
lack of Sync on error types

### ISSUE THREAD

**Issue by jmhodges-signal** [jni-rs/jni-rs#233]
The use of `error_chain` in `jni` means that the error types generated are `!Sync` which means errors can't be carried across threads (as well as colliding with code using `anyhow`).

It'd be nice to use `thiserror` instead which includes `Sync` and other useful bits.

**Comment by jmhodges-signal** [comment]
If there's interest, I'm happy to provide a PR!

**Comment by DarkEld3r** [comment]
`error_chain` is somewhat outdated, though I feel a little bit lost in the latest trends of error handling in Rust.

@vitvakatu Any opinions?

**Comment by DarkEld3r** [comment]
Having thought a bit more about it, I now believe it’s a good idea.
