### ISSUE TITLE
Support Invocation API on Android

### ISSUE THREAD

**Issue by nerdyverde** [jni-rs/jni-rs#236]
When attempting to use the invocation API with Android, I get the following linker error:

> i686-linux-android/bin/ld: error: cannot find -ljli

I'm assuming that this should be attempting to link to libdvm.so on Android, but build.rs doesn't seem to have any configuration options for Android.

**Comment by dmitry-timofeev** [comment]
Is launching a JVM supported on Android? It seems to be the only functionality of the Invocation API that requires linking to libjvm:

https://docs.rs/jni/0.16.0/jni/struct.JavaVM.html#launching-jvm-from-rust
https://github.com/jni-rs/jni-rs/blob/master/src/wrapper/java_vm/vm.rs#L147 

The rest of the methods must work without this feature (e.g., [`AttachCurrentThread`](https://docs.rs/jni/0.16.0/jni/struct.JavaVM.html#attaching-native-threads)).

**Comment by nerdyverde** [comment]
@dmitry-timofeev Thanks for the quick reply. I was mistakenly thinking that I needed the invocation feature in order to use JavaVM. Your comment help me realize my misunderstanding and I'm now happily passing a JavaVM between threads.

**Comment by Zack-Xb** [comment]
Hi @nerdyverde @dmitry-timofeev any idea how this was solved, how we can use javaVM from android without the invocation api. How can one have an instance of JavaVM without launching it ?

**Comment by argv-minus-one** [comment]
@Zack-Xb There is a [`get_java_vm`](https://docs.rs/jni/0.21.1/jni/struct.JNIEnv.html#method.get_java_vm) method on the `JNIEnv` that's passed to your native method implementation. That will give you a `JavaVM`.

**Comment by rib** [comment]
@Zack-Xb for Android specifically there is also this [ndk-context](https://github.com/rust-mobile/ndk-context) (https://crates.io/crates/ndk-context) that can give you access to the JavaVM, even though you may not have implemented any native methods.

For example the `android-activity` crate will initialized the `ndk-context` state for standalone, native Rust applications on Android.

**Comment by Zack-Xb** [comment]
Hey @rib yes that's exactly what I used, I have successfully linked android keystore interaction through rust now through jni-rs. Thank you.
