### ISSUE TITLE
How to get details of JavaException?

### ISSUE THREAD

**Issue by i-schuetz** [jni-rs/jni-rs#238]
Printing an error only shows this:
`error: Error(JavaException, State { next_error: None, backtrace: InternalBacktrace })`

How can I see the exception details?

**Comment by maurolacy** [comment]
Hello Ivan,

Try setting the `RUST_BACKTRACE` env var:
`export RUST_BACKTRACE=1`

Good luck,

**Comment by i-schuetz** [comment]
Ah, thanks! The message about setting it went away but it didn't show anything. I was able to figure out the problem by context though.
