### ISSUE TITLE
How can I use jcharArray as parameter in rust method?

### ISSUE THREAD

**Issue by hero5512** [jni-rs/jni-rs#241]
I find the Object field has JString, but I can't find JCharArray in it. So how can I use it

**Comment by DarkEld3r** [comment]
Could you please provide more details? How does that rust method look like?

**Comment by hero5512** [comment]
> Could you please provide more details? How does that rust method look like?
The following is C library interface. Now I want to transfer it into Java library, but It seems that Java doesn't support pointer type. In addition, I don't know how to use the char array type or long type as the parameter in rust. That's all. THX.

mod generators;
mod bbsplus;
mod accumulator;
mod bulletproofs;
mod issuer;
mod credential;
mod utils;

use issuer::*;
use credential::*;
use utils::*;

use ff::{Field};
use pairing::{
    Engine,
    bls12_381::*,
};

use std::ffi::{CStr, CString};
use std::ptr::{null, null_mut};
use std::os::raw::{c_char, c_int};
use std::error::Error;

use serde_json::{Value, from_str, to_string, json};


const ISSUER_PUBLIC_SIZE: usize = 928;
const ACC_VALUE_SIZE: usize = 96;
const ACC_WITNESS_SIZE: usize = 96 * 3 + 48 + 8;

#[no_mangle]
pub extern "system" fn new_issuer() -> *mut Issuer<Bls12> {
    Box::into_raw(Box::new(Issuer::<Bls12>::new()))
}

#[no_mangle]
pub extern "system" fn free_issuer(
    issuer: *mut Issuer<Bls12>
) {
    drop(unsafe{ Box::from_raw(issuer) });
}

#[no_mangle]
pub extern "system" fn publish_issuer(
    public: *mut [u8; ISSUER_PUBLIC_SIZE],
    issuer: *const Issuer<Bls12>,
) {
    let issuer = unsafe { &*issuer };
    let public = unsafe {&mut *public};
    let p = issuer.publish();
    public.copy_from_slice(&p);
}

#[no_mangle]
pub extern "system" fn get_accumulator_value(
    value: *mut [u8; ACC_VALUE_SIZE],
    issuer: *const Issuer<Bls12>,
) {
    let issuer = unsafe{ &*issuer };
    let mut value = unsafe{ &mut (*value)[..] };
    write_point(&mut value, &issuer.acc.a).unwrap();
}


#[no_mangle]
pub extern "system" fn get_accumulator_info(
    issuer: *const Issuer<Bls12>
) -> *mut c_char {
    let issuer = unsafe{ &*issuer };
    let mut value = vec![];
    write_point(&mut value, &issuer.acc.a).unwrap();

    let a_json = json!({
        "value": base64::encode(&value),
        "latest": issuer.acc.next - 1,
        "deleted": issuer.acc.deleted,
    });
    CString::new(to_string(&a_json).unwrap()).unwrap().into_raw()
}

#[no_mangle]
pub extern "system" fn new_master_secret(ms: *mut [u8; 32]) {
    let s = generate_master_secret::<Bls12>();
    write_f(unsafe{&mut &mut (*ms)[..]}, s).unwrap();
}

#[no_mangle]
pub extern "system" fn make_issue_request(
    ms: *const [u8; 32],
    attr: *const c_char,
    nonce: *const [u8; 16],
    issuer: *const [u8; ISSUER_PUBLIC_SIZE],
) -> *const c_char {
    let ms = read_f::<_, Fr>(unsafe{ &mut &(*ms)[..] }).unwrap();
    let attr_json = unsafe{ CStr::from_ptr(attr) };
    let nonce = unsafe{ *nonce };
    let issuer = match IssuerPublic::<Bls12, _>::from_public(
        unsafe{ &mut &(*issuer)[..] })
    {
        Ok(i) => i,
        Err(e) => {
            eprintln!("issuer error: {}", e);
            return null();
        },
    };

    let jval: Value = from_str(attr_json.to_str().unwrap()).unwrap();
    assert!(jval.is_object());

    let mut attributes = vec![];
    for (_, v) in jval.as_object().unwrap() {
        if v.is_u64() {
            attributes.push(u64_to_field::<Fr>(v.as_u64().unwrap()));
        } else if v.is_boolean() {
            if v.as_bool().unwrap() {
                attributes.push(Fr::one());
            } else {
                attributes.push(Fr::zero());
            }
        } else if v.is_string() {
            attributes.push(
                bytes_to_field::<Fr>(v.as_str().unwrap().as_bytes())
            );
        } else {
            attributes.push(
                bytes_to_field::<Fr>(to_string(&v).unwrap().as_bytes())
            );
        }
    }

    let req = IssueRequest::<Bls12>::new(issuer.seed, ms, attributes, nonce);
    let mut nym = vec![];
    write_point(&mut nym, &req.nym).unwrap();
    let mut proof = vec![];
    write_f(&mut proof, req.c).unwrap();
    write_f(&mut proof, req.s).unwrap();
    base64::encode(&proof);

    let req_json = json!({
        "nym": base64::encode(&nym),
        "zkp": base64::encode(&proof),
        "attributes": jval,
        "nonce": base64::encode(&nonce)
    });
    let jstr = to_string(&req_json).unwrap(); 
    CString::new(jstr).unwrap().into_raw()
}

#[no_mangle]
pub extern "system" fn issue_credential(
    issuer: *mut Issuer<Bls12>,
    request: *const c_char,
) -> *mut c_char {
    let issuer = unsafe{ &mut *issuer };
    let request = unsafe{ CStr::from_ptr(request) };


    let cred = match || -> Result<Credential<Bls12>, Box::<dyn Error>> {
        let request: Value = from_str(request.to_str()?)?;

        let mut attributes = vec![None];
        // master secret is the first attribute, which is committed
        for (_, v) in request["attributes"].as_object().ok_or("not object")? {
            if v.is_u64() {
                attributes.push(Some(
                    u64_to_field::<Fr>(v.as_u64().unwrap())
                ));
            } else if v.is_boolean() {
                if v.as_bool().unwrap() {
                    attributes.push(Some(Fr::one()));
                } else {
                    attributes.push(Some(Fr::zero()));
                }
            } else if v.is_string() {
                attributes.push(Some(
                    bytes_to_field::<Fr>(v.as_str().unwrap().as_bytes())
                ));
            } else {
                attributes.push(Some(
                    bytes_to_field::<Fr>(to_string(&v).unwrap().as_bytes())
                ));
            }
        }

        let data = base64::decode(request["nym"].as_str().unwrap()).unwrap();
        let nym = read_point::<_, <Bls12 as Engine>::G1>(&mut &data[..]).unwrap();

        let zkp = base64::decode(request["zkp"].as_str().unwrap()).unwrap();
        assert_eq!(zkp.len(), 64);
        let c = utils::read_f::<_, Fr>(&mut &zkp[..32]).unwrap();
        let s = utils::read_f::<_, Fr>(&mut &zkp[32..]).unwrap();
        let nonce = base64::decode(request["nonce"].as_str().unwrap()).unwrap();
        if !IssueRequest::<Bls12>::validate(issuer.seed, nym, c, s, &nonce) {
            Err("invalid proof for nym")?;
        }
        Ok(Credential::issue(issuer, &attributes, nym))
    }() {
        Ok(v) => v,
        Err(e) => {
            eprintln!("issue credential error: {}", e);
            return null_mut();
        },
    };

    let mut sig = vec![];
    cred.sig.write(&mut sig).unwrap();
    let cred_json = json!({
        "id": cred.id,
        "witness": base64::encode(&cred.wit.to_bytes().unwrap()),
        "signature": base64::encode(&sig)
    });
    CString::new(to_string(&cred_json).unwrap()).unwrap().into_raw()
}

#[no_mangle]
pub extern "system" fn revoke_credential(
    issuer: *mut Issuer<Bls12>,
    id: u64,
) -> c_int {
    let issuer = unsafe{ &mut *issuer };
    match issuer.acc.delete(id) {
        Ok(_) => 0,
        Err(e) => {
            eprintln!("revoke error, {}", e);
            return -1;
        },
    }
}

#[no_mangle]
pub extern "system" fn extract_witness(
    witness: *mut [u8; ACC_WITNESS_SIZE],
    cred: *const c_char,
) -> c_int {
    let cred = unsafe{ CStr::from_ptr(cred) };
    let buf = match || -> Result<Vec<u8>, Box<dyn Error>>{
        let c: Value = from_str(cred.to_str()?)?;
        let buf = base64::decode(
            c["witness"].as_str().ok_or("witness is not a base64 string")?)?;
        Ok(buf)
    }() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("parse witness from credential error: {}", e);
            return -1;
        },
    };
    assert_eq!(buf.len(), ACC_WITNESS_SIZE);
    let witness = unsafe{ &mut *witness };
    witness.copy_from_slice(&buf);
    return 0;
}


#[no_mangle]
pub extern "system" fn update_witness(
    witness: *mut [u8; ACC_WITNESS_SIZE],
    issuer: *mut Issuer<Bls12>,
    id: u64,
    is_add: u8,
) -> c_int {
    let issuer = unsafe{ &mut *issuer };
    let mut witness = unsafe{ *witness };
    let mut wit = match accumulator::Witness::<Bls12>::read(&mut &witness[..]){
        Ok(w) => w,
        Err(_) => {
            eprintln!("invalid witness");
            return -1;
        },
    };

    issuer.acc.update_witness(&mut wit, id, is_add == 1);
    wit.write(&mut &mut witness[..]).unwrap();

    0
}

#[no_mangle]
pub extern "system" fn update_credential_witness(
    cred: *mut c_char,
    issuer_public: *const [u8; ISSUER_PUBLIC_SIZE],
    witness: *const [u8; ACC_WITNESS_SIZE],
    acc: *const [u8; ACC_VALUE_SIZE]
) -> c_int {
    let issuer = unsafe{ &*issuer_public };
    let witness = unsafe{ *witness };
    let acc = unsafe{ &mut &(*acc)[..] };

    let issuer = match IssuerPublic::<Bls12, _>::from_public(issuer) {
        Ok(iss) => iss,
        Err(e) => {
            eprintln!("invalid issuer, {}", e);
            return -1;
        }
    };
    let wit = match accumulator::Witness::<Bls12>::read(&mut &witness[..]){
        Ok(w) => w,
        Err(_) => {
            eprintln!("invalid witness");
            return -1;
        },
    };
    let a = match read_point::<_, <Bls12 as Engine>::G2>(acc) {
        Ok(a) => a,
        Err(e) => {
            eprintln!("invalid accumulator value, {}", e);
            return -1;
        }
    };

    if !issuer.ap.verify(a, &wit) {
        eprintln!("accumulator verification failed, invalid value or witness");
        return -1;
    }

    let cred_json = match unsafe{ CStr::from_ptr(cred).to_str() } {
        Ok(s) => s,
        Err(_) => {
            eprintln!("credential is not a string");
            return -1;
        }
    };
    let mut cred_json: Value = match from_str(cred_json) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("credential is not a valid json, {}", e);
            return -1;
        }
    };
    if !cred_json.is_object() {
        eprintln!("invalid credential format");
        return -1;
    }

    cred_json["witness"] = json!(base64::encode(&wit.to_bytes().unwrap()));
    let json_str = to_string(&cred_json).unwrap();
    unsafe {
        std::ptr::copy(json_str.as_ptr(), cred as * mut u8, json_str.len());
    }

    0
}

#[no_mangle]
pub extern "system" fn present(
    cred: *const c_char,
    ms: *const [u8; 32],
    attr: *const c_char,
    issuer: *const [u8; ISSUER_PUBLIC_SIZE],
    acc: *const [u8; ACC_VALUE_SIZE],
    nonce: *const[u8; 16],
) -> *mut c_char {
    let ms = read_f::<_, Fr>(unsafe{ &mut &(*ms)[..] }).unwrap();
    let issuer = unsafe{ &*issuer };
    let cred = unsafe{ CStr::from_ptr(cred) };
    let attr = unsafe{ CStr::from_ptr(attr) };
    let acc = unsafe{ &mut &(*acc)[..] };
    let nonce = unsafe{ *nonce };

    let pre_json = match || -> Result<Value, Box<dyn Error>> {
        let issuer = IssuerPublic::<Bls12, _>::from_public(issuer)?;
        let cred_json: Value = from_str(cred.to_str()?)?;
        let mut attr_json: Value = from_str(attr.to_str()?)?;
        let acc = read_point::<_, <Bls12 as Engine>::G2>(acc)?;

        let id = cred_json["id"].as_u64().ok_or("id is not u64")?;
        let buf = base64::decode(
            cred_json["witness"].as_str()
                                .ok_or("witness is not a base64 string")?
        )?;
        let wit = accumulator::Witness::<Bls12>::read(&mut &buf[..])?;
        let buf = base64::decode(
            cred_json["signature"].as_str()
                                  .ok_or("signature is not a bse64 string")?
        )?;
        let sig = bbsplus::Signature::<Bls12>::read(&mut &buf[..])?;
        let cred = Credential{id, wit, sig};

        let mut attributes = vec![];
        for (_, v) in attr_json.as_object()
                               .ok_or("attributes is not a json object")? {
            if !v.is_object() {
                Err("each attribute should be a json object")?;
            }
            let mut att = Attribute::<Bls12>::default();
            att.value = {
                let v = &v["value"];
                if v.is_u64() {
                    u64_to_field::<Fr>(v.as_u64().unwrap())
                } else if v.is_boolean() {
                    if v.as_bool().unwrap() {
                        Fr::one()
                    } else {
                        Fr::zero()
                    }
                } else if v.is_string() {
                        bytes_to_field::<Fr>(v.as_str().unwrap().as_bytes())
                } else {
                        bytes_to_field::<Fr>(to_string(&v).unwrap().as_bytes())
                }
            };
            let st = v["state"].as_str().ok_or("invalid state")?;
            if st == "disclose" {
                att.state = AttributeState::VALUE;
            } else if st == "range" {
                let a = v["range"][0].as_u64().ok_or("invalid range")?;
                let b = v["range"][1].as_u64().ok_or("invalid range")?;
                att.state = AttributeState::RANGEPROOF(a, b);
            } else if st == "hide" {
                att.state = AttributeState::HIDDEN;
            } else {
                Err("unexpected attribute state")?;
            }
            attributes.push(att);
        }

        let pre = Presentation::present::<merlin::Transcript, _>(
            ms, &issuer, &mut attributes, &cred, acc, nonce);
        let mut proof = vec![];
        pre.write(&mut proof).unwrap();

        let mut i = 0;
        for (_, v) in attr_json.as_object_mut().unwrap() {
            if attributes[i].state != AttributeState::VALUE {
                v.as_object_mut().unwrap().remove("value");
            }
            match attributes[i].state{
                AttributeState::RANGEPROOF(_, _) => {
                    let mut buf = vec![];
                    write_f(&mut buf, attributes[i].blinding).unwrap();
                    let obj = v.as_object_mut().unwrap();
                    obj.insert(String::from("blinding"),
                            Value::String(base64::encode(&buf)));
                    let mut buf1 = vec![];
                    write_point(&mut buf1, &attributes[i].commitment).unwrap();
                    obj.insert(String::from("commitment"),
                                Value::String(base64::encode(&buf1)));
                },
                _ => (),
            }
            i += 1;
        }

        let pre_json = json!({
            "attributes": attr_json,
            "proof": base64::encode(&proof)
        });

        Ok(pre_json)
    } () {
        Ok(res) => res,
        Err(e) => {
            return null_mut();
        },
    };

    CString::new(to_string(&pre_json).unwrap()).unwrap().into_raw()
}

#[no_mangle]
pub extern "system" fn verify(
    present: *const c_char,
    issuer: *const [u8; ISSUER_PUBLIC_SIZE],
    acc: *const [u8; ACC_VALUE_SIZE],
    nonce: *const [u8; 16],
) -> c_int {
    let issuer = unsafe{ &*issuer };
    let present = unsafe{ CStr::from_ptr(present) };
    let acc = read_point::<_, <Bls12 as Engine>::G2>(unsafe{&mut &(*acc)[..]}).unwrap();
    let nonce = unsafe{ *nonce };

    let ok = match || -> Result<bool, Box<dyn Error>> {
        let issuer = IssuerPublic::<Bls12, _>::from_public(issuer)?;
        let pre_json: Value = from_str(present.to_str()?)?;
        let mut attributes = vec![];
        for (_, v) in pre_json["attributes"].as_object()
                                            .ok_or("not a json object")? {
            if !v.is_object() {
                Err("each attribute should be a json object")?;
            }
            let mut att = Attribute::<Bls12>::default();
            let st = v["state"].as_str().unwrap();
            if st == "disclose" {
                att.state = AttributeState::VALUE;
                att.value = {
                    let v = &v["value"];
                    if v.is_u64() {
                        u64_to_field::<Fr>(v.as_u64().unwrap())
                    } else if v.is_boolean() {
                        if v.as_bool().unwrap() {
                            Fr::one()
                        } else {
                            Fr::zero()
                        }
                    } else if v.is_string() {
                            bytes_to_field::<Fr>(v.as_str().unwrap().as_bytes())
                    } else {
                            bytes_to_field::<Fr>(to_string(&v).unwrap().as_bytes())
                    }
                };
            } else if st == "range" {
                let a = v["range"][0].as_u64().ok_or("invalid range")?;
                let b = v["range"][1].as_u64().ok_or("invalid range")?;
                att.state = AttributeState::RANGEPROOF(a, b);
                let buf = base64::decode(
                    v["blinding"].as_str().ok_or("invalid blinding")?
                )?;
                att.blinding = read_f::<_, Fr>(&mut &buf[..])?;
                let buf = base64::decode(
                    v["commitment"].as_str().ok_or("invalid commitment")?
                )?;
                att.commitment = read_point::<_, <Bls12 as Engine>::G1>(
                    &mut &buf[..]
                )?;
            } else if st == "hide" {
                att.state = AttributeState::HIDDEN;
            } else {
                Err("unexpected attribute state")?;
            }
            attributes.push(att);
        }

        let proof = base64::decode(
            pre_json["proof"].as_str().ok_or("invalid proof")?
        )?;
        let pre = Presentation::<Bls12>::read(&mut &proof[..]).unwrap();

        Ok(pre.verify::<merlin::Transcript, _>(
            &issuer, &attributes, &acc, nonce
        )) 
    } () {
        Ok(b) => b,
        Err(e) => {
            eprintln!("verification error: {}", e);
            return -1;
        },
    };

    if ok {
        0
    } else {
        -1
    }
}


#[no_mangle]
pub extern "system" fn free_str(s: *mut c_char) {
    drop(unsafe{ CString::from_raw(s) });
}


use std::io;

impl accumulator::Serialize for Fq12 {
    fn size() -> usize {
        12 * 48
    }

    fn write<W: io::Write>(&self, w: &mut W) -> io::Result<()> {
        write_f(w, self.c0.c0.c0)?;
        write_f(w, self.c0.c0.c1)?;
        write_f(w, self.c0.c1.c0)?;
        write_f(w, self.c0.c1.c1)?;
        write_f(w, self.c0.c2.c0)?;
        write_f(w, self.c0.c2.c1)?;
        write_f(w, self.c1.c0.c0)?;
        write_f(w, self.c1.c0.c1)?;
        write_f(w, self.c1.c1.c0)?;
        write_f(w, self.c1.c1.c1)?;
        write_f(w, self.c1.c2.c0)?;
        write_f(w, self.c1.c2.c1)?;
        Ok(())
    }

    fn read<R: io::Read>(r: &mut R) -> io::Result<Self> {
        let c000 = read_f(r)?;
        let c001 = read_f(r)?;
        let c010 = read_f(r)?;
        let c011 = read_f(r)?;
        let c020 = read_f(r)?;
        let c021 = read_f(r)?;
        let c100 = read_f(r)?;
        let c101 = read_f(r)?;
        let c110 = read_f(r)?;
        let c111 = read_f(r)?;
        let c120 = read_f(r)?;
        let c121 = read_f(r)?;
        Ok(Fq12{
            c0: Fq6{
                c0: Fq2{c0: c000, c1: c001},
                c1: Fq2{c0: c010, c1: c011},
                c2: Fq2{c0: c020, c1: c021},
            },
            c1: Fq6{
                c0: Fq2{c0: c100, c1: c101},
                c1: Fq2{c0: c110, c1: c111},
                c2: Fq2{c0: c120, c1: c121},
            },
        })
    }

}

**Comment by DarkEld3r** [comment]
Sorry, I still don't understand what issue you have.

Do you have `JCharArray` and want to work with it in Rust? In that case you can use `get_array_length` and `get_char_array_region` functions.
