### ISSUE TITLE
`define_class` with null name

### ISSUE THREAD

**Issue by cookiedragon234** [jni-rs/jni-rs#245]
At the moment it is impossible to provide a null name to `env.define_class`, as is allowed in JNI, which means the class name is found from the contents of the provided class bytes.

A potential solution could be to change the constraint on define class from:
```Rust
where
    S: Into<JNIString>,
```
To:
```Rust
where
	S: Into<*const c_char>
```

Would this change be acceptable? JNIString could be modified to implement `Into<*const c_char>`.

This would allow code like the following:
```Rust
define_class(null(), ...);
define_class(CString::new("ClassName").unwrap().as_ptr(), ...);
```

**Comment by cookiedragon234** [comment]
Adding the following would make JNIString still available as a parameter:
```Rust
impl Into<*const c_char> for JNIString {
	fn into(self) -> *const c_char {
		self.internal.as_ptr()
	}
}
```

**Comment by DarkEld3r** [comment]
I'm not sure about `Into<*const c_char>`. Perhaps it would be better to change `define_class` signature to the following:
```rust
fn define_class<S>(&self, name: Option<S>, loader: JObject<'a>, buf: &[u8]) -> Result<JClass<'a>>
    where
        S: Into<JNIString>,
```

**Comment by DarkEld3r** [comment]
One more idea: we can add a different function, something like:
```rust
fn define_unnamed_class(&self, loader: JObject<'a>, buf: &[u8]) -> Result<JClass<'a>>
```
Personally I like this approach more.
