### ISSUE TITLE
Can't get JNI work on windows.

### ISSUE THREAD

**Issue by Josef-Vonasek** [jni-rs/jni-rs#246]
I have followed the `hello` example, but I get stuck after [cargo build](https://docs.rs/jni/0.17.0/jni/#the-rust-side)

My `target/debug` doesn't contain `libmylib.dll`. 
Instead it contains `lib.dll` and `libmylib.rlib`. None of which works when loaded in java.

**Comment by DarkEld3r** [comment]
Sorry for the late reply. Were you able to find the solution to this issue?

**Comment by Josef-Vonasek** [comment]
Yup, `lib.dll` was the correct file. It just didn't load, because I had a typo in the interface.

**Comment by DarkEld3r** [comment]
@Josef-Vonasek Glad to hear that everything is working. :+1:
