### ISSUE TITLE
Logo for jni-rs organization

### ISSUE THREAD

**Issue by stanislav-tkach** [jni-rs/jni-rs#248]
I think it would be nice to have a logo instead of a generated placeholder. I suppose it can be simple, but unfortunately I don't have the required skills and the best that I can propose is the following:
![jni_logo](https://user-images.githubusercontent.com/2997902/91903117-5baf4f80-ecab-11ea-9e61-4a6dfa417afe.png)

@jrobsonchase It would be nice to hear your opinion on this as well.

**Comment by dmitry-timofeev** [comment]
That's a good idea! Unfortunately, I am not a graphic designer either :-) 

Reminds me of an ingenious sticker Dmitry Lagoda did for Exonum Java Binding: an owl in a Java coffee cup with a Rust-cookie :-) 

![PSX_20200912_143635](https://user-images.githubusercontent.com/7531824/92994748-9adc6c80-f505-11ea-90fd-68f0b2525ab3.jpg)

**Comment by hoangpq** [comment]
![jni-rs-logo](https://user-images.githubusercontent.com/5939997/133093025-93367aeb-0a76-4329-b4f9-fd178c619eb5.png)

Hi @stanislav-tkach @dmitry-timofeev, I created a simple logo for jni-rs org. Feel free to use :)

SVG file: [rsjni-logo_01.svg.zip](https://github.com/jni-rs/jni-rs/files/7154701/rsjni-logo_01.svg.zip)

**Comment by stanislav-tkach** [comment]
@hoangpq Thanks, I really like your logo!

**Comment by stanislav-tkach** [comment]
Unfortunately, I'm unable to change the organization avatar. @jrobsonchase What do you think?

**Comment by rib** [comment]
Hey this is a very nice logo @hoangpq - thanks! I've just set it as the image for the organisation and it may just take a little while to propagate.

**Comment by hoangpq** [comment]
@rib I'm so glad to hear that <3

**Comment by rib** [comment]
Going to close this issue now that we've set this as the logo for the organization.

Thanks again for creating this logo @hoangpq!
