### ISSUE TITLE
Resolving Data Type from JObject?

### ISSUE THREAD

**Issue by iamchairs** [jni-rs/jni-rs#254]
I have searched through the documentation, examples, and source but I'm having trouble figuring out how to get a data type (and ultimately it's value) from a JObject.

My method takes a `HashMap<String, Object>` (`JMap`) where the value of the hashmap may be anything.

```
let fields: JMap = env.get_map(flds).expect("Couldn't get java hashmap").into();
    let mut fields_iter = fields.iter().unwrap();

    let mut done = false;
    while !done {
        match fields_iter.next() {
            Some(item) => {
                let key: String = env.get_string(JString::from(item.0))
                    .expect("Couldn't get map key as string").into();

                let value = item.1;
                // What type is value??
            },
            None => {
                done = true;
            }
        }
    }
```

I was hoping to at least get the fully qualified class name from the `Desc` interface but for `JObject` it just returns a `JClass` - which doesn't seem helpful.

**Comment by dmitry-timofeev** [comment]
The type you see in JNI is `JObject`. If you'd like to get the actual class of the referenced Object in native, you have to call `Object#getClass`. For example, like this code does: https://github.com/exonum/exonum-java-binding/blob/d4978fa8fde56b1dd86652bf84513d924b237846/exonum-java-binding/core/rust/src/utils/jni.rs#L34-L41 

`Desc` exists to support various descriptors of classes and method/field IDs (e.g., both strings and JClass for classes; strings and IDs fror method IDs).

**Comment by iamchairs** [comment]
Thanks for the response. I was able to get some help from here so I will close this.

https://stackoverflow.com/questions/63946475/converting-unknown-java-types-to-rust-types/63947243#63947243
