### ISSUE TITLE
Resolve Travis CI configuration

### ISSUE THREAD

**Issue by dmitry-timofeev** [jni-rs/jni-rs#256]
Travis CI does not seem to perform PR builds, staying in status "Waiting". 

Possibly, an Application integration needs to be added, but I don't have rights for that. 

I disabled Travis CI for PRs, and made Appveyor (Windows only) required.

**Comment by stanislav-tkach** [comment]
Not sure how to deal with Travis, but I will try to finish #240. Github actions are verbose in some cases, but I still find them more convenient than having several different CI services.

**Comment by rib** [comment]
Closing this, since I'm assuming for now that since #240 landed everyone is happy to stick with github actions for CI instead of re-enabling Travis CI
