### ISSUE TITLE
Implement `TryInto<T>` for JValue with types that implement `Into<JValue>`

### ISSUE THREAD

**Issue by giovanniberti** [jni-rs/jni-rs#262]
Hi, I'm working on a library that interfaces with `jni` and it would make my life *a lot* easier if types that implement `Into<JValue>` (e.g. `bool`, `f32`, `JObject`, etc...) implemented `TryInto`, e.g. by simply calling the already defined methods `z()`, `f()`, etc. I don't see any technical limitations to this.

The end result would be something like:

```rust
let raw: JValue = /* some JValue */;
let value: Result<i32> = raw.try_into();
/* do something with `value` */
```

If you are ok with this I could even implement the necessary code and follow through with a PR. :smiley:

**Comment by stanislav-tkach** [comment]
Hey and sorry for the late reply!

Your suggestion sounds good to me. I think it definitely improves the ergonomics of this library. Looking forward to see your pull request!
