### ISSUE TITLE
how to call java methods from rust code outside native methods

### ISSUE THREAD

**Issue by abnud1** [jni-rs/jni-rs#263]
I'm currently passing java's `InputStream` to rust code and I want to implement `std::io::Read` trait for it so That I can pass it to libraries expecting the trait.

The problem is that `impl Read for InputStreamStruct` is done outside any native method, I'm already using `GlobalRef` and tried storing JNIEnv in the `InputStreamStruct` but I get segmentation fault because of that.

Here is my current code:
```rust

struct InputStream {
    executor: Executor,
    input_stream_ref: GlobalRef,
}
impl InputStream {
    fn new(executor: Executor, input_stream_ref: GlobalRef) -> InputStream {
        InputStream {
            executor,
            input_stream_ref,
        }
    }
}
impl Read for InputStream {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        let input_stream = self.input_stream_ref.as_obj();
        let executor = &self.executor;
        executor
            .with_attached(|env| {
                let byte = env.call_method(input_stream, "read", "()I", &[]);
                if byte.is_ok() {
                    let byte: u8 = byte.unwrap().i().expect("expected an integer") as u8;
                    buf[0] = byte;
                    return Ok(1);
                }
                return Err(jni::errors::Error::from(
                    "failed to read next byte from input stream",
                ));
            })
            .map(|i| i as usize)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.description()))
    }
}

#[no_mangle]
pub extern "system" fn Java_io_jvmbrotli_CustomInputStream_createStream(
    env: JNIEnv,   
    _class: JClass,
    input_stream: JObject,
) -> jlong {
    let java_vm = env
        .get_java_vm()
        .expect("failed to get JavaVM object from JNIENV");
    let input_stream_ref = env
        .new_global_ref(input_stream)
        .expect("failed to create global reference to input stream");
    let executor = Executor::new(Arc::new(java_vm));
    let input_stream = InputStream::new(executor, input_stream_ref);
    return Box::into_raw(Box::new(input_stream)) as jlong;
}

#[no_mangle]
pub extern "system" fn Java_io_jvmbrotli_BrotliInputStream_readNative(
    _env: JNIEnv,
    _class: JClass,
    input_stream_pointer: jlong,
) -> jint {
    let mut input_stream = unsafe { Box::from_raw(input_stream_pointer as *mut InputStream) };
    let mut buf: [u8; 1] = [0; 1];
    let result = input_stream.read(&mut buf);
    if result.is_err() || result.unwrap() == 0 {
        return -1;
    }
    buf[0] as jint
}
```

With this code the segmentation fault happens at `jni::wrapper::java_vm::vm::JavaVM::get_env`, previously when storing env I get segmentation fault at `as_obj` line, I tried attaching to the current thread as a daemon in native method and later used the env resulting from attachment, that resulted in a segmentation fault at `env.call_method` line.

So how do I call java's `InputStream.read` from a trait impl?

**Comment by dmitry-timofeev** [comment]
Regarding the question on how to call the Java code outside native methods, your usage seems correct: you need to attach a native thread to obtain a JNIEnv (see also the spec on [attaches](https://docs.oracle.com/en/java/javase/14/docs/specs/jni/invocation.html#attaching-to-the-vm) and [ref management](https://docs.oracle.com/en/java/javase/14/docs/specs/jni/design.html#referencing-java-objects); and [jni-rs specific documentation](https://docs.rs/jni/0.17.0/jni/struct.JavaVM.html#attaching-native-threads)). 

jni-rs provides:
- Executor to make it easier to safely attach native threads (with no leaks of threads; no threads preventing VM exit) and do that once per thread for repeated calls in unbounded context.
- GlobalRef to prevent global ref leaks.

As you mentioned segmentation faults, I'd suspect the conversion from pointer to an object; but I haven't inspected that code in a lot of detail. In EJB we used a special module to bring back some type-safety lost at FFI boundary in debug builds: https://github.com/exonum/exonum-java-binding/blob/master/exonum-java-binding/core/rust/src/handle/mod.rs I highly recommend adopting it, as it saved us a lot of time on debugging when we attempted to pass a wrong handle/cast it to a wrong type.

**Comment by abnud1** [comment]
Thanks A Lot, I know the problem now, the problem is by using `Box::from_raw` I get a `Box` variable which is dropped at the end of function scope causing memory held by Box to be freed which caused the segmentation fault.
