### ISSUE TITLE
Last Pinned Release is 0.13.0

### ISSUE THREAD

**Issue by Onirik79** [jni-rs/jni-rs#267]
In the main page of the project it is indicated, pinned on the right, as the latest version 0.13.0. But the latest crate version is 0.17.0
Is 0.13.0 to be considered the last stable one?

**Comment by stanislav-tkach** [comment]
We have just forgotten to publish release information on the Github. :sweat_smile: I'm going to fix that.

**Comment by stanislav-tkach** [comment]
Done. Feel free to reopen the issue if you have more questions about the releases.

**Comment by dmitry-timofeev** [comment]
@stanislav-tkach thanks for that, I stopped doing that as the releases were small. I guess the other tools in the ecosystem can extract the relevant bits (= dependabot, crates.io). 

Is there a github action cutting the relevant bits from the changelog once a release tag is pushed?

**Comment by stanislav-tkach** [comment]
There are some release related actions (for example https://github.com/actions/create-release), but I haven't checked what exactly they do.

**Comment by dmitry-timofeev** [comment]
OK, created https://github.com/jni-rs/jni-rs/issues/277
