### ISSUE TITLE
How to get a rust array (or alternatively a jobjectarray) from a JValue (or alternatively from a JObject)?

### ISSUE THREAD

**Issue by Onirik79** [jni-rs/jni-rs#269]
I have a java method which, invoked with env.call_method, returns an array of Class.
The signature therefore is:
()[Ljava/lang/reflect/Class;

env.call_method returns a value of type JValue which I can convert to JObject with l.().unwrap()
But if I want to get an jobjectarray (or rust array directly) how can I do?

Sorry for the newbie question, I'm trying to learn rust, jni and jni-rs at the same time!

**Comment by maurolacy** [comment]
A `JObject` is (or can be) just a wrapper around a `jobjectArray`.

Just look at the definitions. A `jobjectArray` is a `jArray` is a `jobject`,
whereas a `JObject` is
```
pub struct JObject<'a> {
    internal: jobject,
    lifetime: PhantomData<&'a ()>,
}
```.
That is, a `jobject` with a lifetime.

So, you already have what you need. If you just pass your `JObject` to a method like `get_object_array_element()`, it should work.

**Comment by Onirik79** [comment]
It works! I actually had to de-reference it.
Thank you!
