### ISSUE TITLE
Get array elements error

### ISSUE THREAD

**Issue by maurolacy** [jni-rs/jni-rs#283]
Get array elements test are [failing](https://github.com/jni-rs/jni-rs/pull/282/checks?check_run_id=1343885451):

The error is:
```
ReleasePrimitiveArrayCritical: release array failed bounds check, incorrect pointer returned ? array: 0x00007f4de007bc40 carray: 0x00007f4dd8001260
GuardedMemory(0x00007f4de445c420) base_addr=0x00007f4dd8001240 tag=0x00007f4dd8001720 user_size=24 user_data=0x00007f4dd8001260
  Header guard @0x00007f4dd8001240 is BROKEN
  Trailer guard @0x00007f4dd8001278 is OK
  User data appears to have been freed
FATAL ERROR in native method: ReleasePrimitiveArrayCritical: failed bounds check
```

**Comment by maurolacy** [comment]
So far, I've seen that this happens when calling `commit()` on the auto array, and doesn't seem related to changes / state of the array. It's also independent of the `ReleaseMode`. So, this is weird / looks like a low level bug of some kind.

Easiest/shortest way to reproduce:
```
#[test]
pub fn get_byte_array_elements_commit() {
    let env = attach_current_thread();

    // Create original Java array
    let buf: &[u8] = &[1, 2, 3];
    let java_array = env
        .byte_array_from_slice(buf)
        .expect("JNIEnv#byte_array_from_slice must create a java array from slice");

    let mut auto_ptr = env
        .get_byte_array_elements(java_array, ReleaseMode::CopyBack)
        .unwrap();

    auto_ptr.commit().unwrap();
}
```

**Comment by maurolacy** [comment]
This bug is related to the JDK version:
With OpenJDK 8:
```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ caro test --features=invocation --test jni_api get_byte_array_elements_commit
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/jni_api-11d0bfae9609f536

running 1 test
test get_byte_array_elements_commit ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 48 filtered out
$ 
```

With OpenJDK 11:
```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1deb10u1, mixed mode, sharing)
$ cargo test --features=invocation --test jni_api get_byte_array_elements_commit
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/jni_api-11d0bfae9609f536

running 1 test
ReleasePrimitiveArrayCritical: release array failed bounds check, incorrect pointer returned ? array: 0x00007f6fd40f6180 carray: 0x00007f6fd415b750
GuardedMemory(0x00007f6fd98cdb00) base_addr=0x00007f6fd415b730 tag=0x00007f6fd40162f0 user_size=3 user_data=0x00007f6fd415b750
  Header guard @0x00007f6fd415b730 is BROKEN
  Trailer guard @0x00007f6fd415b753 is OK
  User data appears to have been freed
FATAL ERROR in native method: ReleasePrimitiveArrayCritical: failed bounds check
error: test failed, to rerun pass '--test jni_api'

Caused by:
  process didn't exit successfully: `/usr2/home/mauro/work/jni-rs/target/debug/deps/jni_api-11d0bfae9609f536 get_byte_array_elements_commit` (signal: 6, SIGABRT: process abort signal)
$ 
```

**Comment by maurolacy** [comment]
So, this looks like a JDK / JNI bug (or limitation?). Not sure how to proceed from here. You probably know better than me, but contacting the OpenJDK teams looks like the next thing to do.

I've searched for "FATAL ERROR in native method: ReleasePrimitiveArrayCritical" and didn't found much:
[1](https://stackoverflow.com/questions/48332223/fatal-error-in-native-method-releaseprimitivearraycritical-failed-bounds-check)
[2](https://developer.ibm.com/languages/java/articles/j-jni/)

**Comment by maurolacy** [comment]
Re-reading [the JNI documentation](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#ReleaseMode), it may be that I originally misunderstood the intent of `JNI_COMMIT` mode. It does not free the native array, but it does free the Java array (!). So, the error is being caused by calling Release two times on the array.

Let me know what you think, but If I'm now right, we should eliminate the `commit()` method from the API, and put `JNI_COMMIT` into the `ReleaseMode` struct, as an alternative release mode: one that releases the Java array, but simply doesn't free the native buffer.

I think this also explains why `JNI_COMMIT` is in the release modes. Despite its name, it is a **release** mode, and must be considered as such.

The example I found in the [IBM best practices page](https://developer.ibm.com/languages/java/articles/j-jni/) support this interpretation (see Listing 12. Including a release call).

**Comment by dmitry-timofeev** [comment]
Great investigation, thanks! Good we had these tests.

Given "commit" essentially transfers ownership over that pointer to the client code, can we really support commit as part of drop? Won't the buffer remain allocated?

Is it possible to modify commit so that it consumes the AutoArray (releases with commit), and returns a pointer wrapped into any safe type that will ensure the buffer is deallocated? If not, we can probably drop "commit" for now.

**Comment by maurolacy** [comment]
I think the safest bet is to remove `commit()` entirely. It arose from a misunderstanding on my part regarding release modes.

**Comment by dmitry-timofeev** [comment]
Agree — let's remove commit, and document how it can be added in an issue in case someone ever needs it (if my description above is correct).

**Comment by maurolacy** [comment]
@dmitry-timofeev I turned `commit()` into a method because my understanding at the time was that it was possible to call ReleaseArrayElements over the array again, later.

But, after seeing these errors, and reading more about the ways to use the API (see IBM Best practices doc above) it now seems clear to me that `JNI_COMMIT` is a release operation; in the sense that calling it again would fail. So, it doesn't make sense to return a pointer from it, because the data it points to would probably be invalidated. In fact if you see my last comments in the related PR thread, that seems to be exactly the case.

`JNI_COMMIT` probably makes sense in a C/C++ environment, where the buffer allocation is being done manually (through `malloc` or `new()`. Here in Rust, it seems that this release mode is not needed / it's equivalent to `CopyBack`.

**Comment by dmitry-timofeev** [comment]
> @dmitry-timofeev I turned commit() into a method because my understanding at the time was that it was possible to call ReleaseArrayElements over the array again, later.

I think your original understanding of the spec is actually correct. I don't see the evidence in the docs that you can commit and forget. I thought you can commit and can keep the pointer, but it doesn't seem to be true (see for instance the JNI tips for Android — though Dalvik is certainly far from the Hotspot):

> Also note that the JNI_COMMIT flag does not release the array, and you will need to call Release again with a different flag eventually.

https://developer.android.com/training/articles/perf-jni 

Also, if you switch off `check:jni`, modify the array after commit, then release it with copy back, the Java array will reflect the modifications made after commit, at least confirming that this works (on 8 and 15). Certainly, it does not confirm that this behaviour is correct according to the spec, but it might also happen that there is a bug in `check:jni` mode 🤷‍♂️ 

Some observations:
- Hotspot always copies: https://github.com/openjdk/jdk/blob/6bc493188b265b1f9776aa62f77c161d75fc591e/src/hotspot/share/prims/jni.cpp#L2577-L2588 
- Android VM may return without copies: https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/jni_internal.cc;l=2670-2673;drc=master 
  - It also handles commit correctly: https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/jni_internal.cc;l=2717;drc=master;bpv=0;bpt=1 (see also the implementation in `check_jni.cc`: https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/check_jni.cc;l=1573-1576;drc=master

**Comment by maurolacy** [comment]
> > @dmitry-timofeev I turned commit() into a method because my understanding at the time was that it was possible to call ReleaseArrayElements over the array again, later.
> 
> I think your original understanding of the spec is actually correct. I don't see the evidence in the docs that you can commit and forget.

The evidence I have for that is scarce, true:
- The name of the JNI methodl, which is Release.
- Never seen a code that makes two Release calls.
- The Best practices doc above, where a final Release with JNI_COMMIT is done.

> I thought you can commit and can keep the pointer, but it doesn't seem to be true (see for instance the JNI tips for Android — though Dalvik is certainly far from the Hotspot):
> 
> > Also note that the JNI_COMMIT flag does not release the array, and you will need to call Release again with a different flag eventually.

That comment may be true of the Android JDK. But, I've never read something like that in the official JNI docs.

We may be hitting some worst case scenario here, in that, or there's an underlying bug in some implementations, or worse, different implementations understood `JNI_COMMIT` differently (like ourselves), and so, it's impossible to provide a consistent calling pattern accross them.

I think the safest bet, until some particular use case or calling pattern appears, would be to remove this release mode entirely.

> 
> https://developer.android.com/training/articles/perf-jni
> 
> Also, if you switch off `check:jni`, modify the array after commit, then release it with copy back, the Java array will reflect the modifications made after commit, at least confirming that this works (on 8 and 15). Certainly, it does not confirm that this behaviour is correct according to the spec, but it might also happen that there is a bug in `check:jni` mode man_shrugging
> 
> Some observations:
> 
>     * Hotspot always copies: https://github.com/openjdk/jdk/blob/6bc493188b265b1f9776aa62f77c161d75fc591e/src/hotspot/share/prims/jni.cpp#L2577-L2588
> 
>     * Android VM may return without copies: https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/jni_internal.cc;l=2670-2673;drc=master
>       
>       * It also handles commit correctly: https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/jni_internal.cc;l=2717;drc=master;bpv=0;bpt=1 (see also the implementation in `check_jni.cc`: https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/check_jni.cc;l=1573-1576;drc=master

**Comment by dmitry-timofeev** [comment]
The Hotspot implementation supports the commit use-case (which I previously verified in tests without "check:jni" mode): https://github.com/openjdk/jdk/blob/6bc493188b265b1f9776aa62f77c161d75fc591e/src/hotspot/share/prims/jni.cpp#L2623-L2639 

JNI check implementation does not distinguish commit from 0, releasing the guarded memory: https://github.com/openjdk/jdk/blob/976acddeb5a8df1e868269787c023306aad3fe4a/src/hotspot/share/prims/jniCheck.cpp#L422-L441 

As the mode is named "commit" (write the changes) and not "copy the contents and transfer the buffer ownership to me"; and that the buffer is allocated inside the JNI library (and it is reasonable for that library to be responsible for freeing the buffer to avoid any issues with allocators), I think there is no discrepancy between Hotspot and Android, but a bug in "check:jni" in Hotspot. Here is a commit introducing this bug: https://github.com/openjdk/jdk/commit/3e904a4801b2bf2e988ba096e5cb64a17fd5fce7 , the issue: https://bugs.openjdk.java.net/browse/JDK-8193234 and a discussion on the mailing list: https://mail.openjdk.java.net/pipermail/hotspot-dev/2017-December/029523.html 

Probably, the best solution would be to study that discussion, confirm our understanding of the spec on an appropriate mailing list, and if there is a bug in "check:jni" — fix it. 

Alternatively, we can:
- Keep the test for commit in a separate file that creates a VM without "check:jni"
- Remove it.

**Comment by maurolacy** [comment]
Great investigation!

I'll study the discussion / threads. I agree that if we can make the functionality stable / consistent, and it's well tested (do jni-rs supports testing under multiple JVMs?), we must keep it. And of course, push for fixes of the underlying JVM bugs, if there are any.

**Comment by maurolacy** [comment]
> I think there is no discrepancy between Hotspot and Android, but a bug in "check:jni" in Hotspot.

Why do you mention "check:jni"? AFAIK, the original bug happens without "-Xcheck:jni" enabled, in both (HotSpot) OpenJDK 11, and recent versions of OpenJDK 8.

**Comment by dmitry-timofeev** [comment]
The JVM for ITs is always created with this flag: 

https://github.com/jni-rs/jni-rs/blob/master/tests/util/mod.rs#L11-L21

**Comment by dmitry-timofeev** [comment]
If you switch it off, tests pass (even the longer one that does writes after committing, and verifies both results on the Java array). Both the observed behaviour and the implementation (without extra checks) confirm that such scenario does work.

**Comment by maurolacy** [comment]
Not much free time these days. I'll follow-up when possible. Feel free to take it if you want.

**Comment by maurolacy** [comment]
OK, I've decided to take this :-)

My plan is to download OpenJDK sources, fix the bug, confirm / test it's fixed, and send a patch to the OpenJDK project.

Any advice is welcome.

**Comment by dmitry-timofeev** [comment]
Sounds great, that's a good way to contribute to one of the biggest projects out there! 

I'd only recommend getting in touch with the maintainers early, so that they are aware of this problem, and can help getting it integrated. CC-ing people from the issue and the list discussions could also help get the right people in the loop.

As OpenJDK is a big project with huge impact, they have strict requirements in terms of project documenation, and won't merge a patch that changes behaviour without a corresponding issue (i.e., if it is not a pure refactoring or document improvements). One of the benefits is that we were able to find by a patch that introduced the bug the issue and the original discussion quickly :)

OpenJDK Jira doesn't allow submitting issues directly, so, again, it makes sense to write to the list or submit an issue through the Oracle site, but in this particular case I think the list might work better.

**Comment by maurolacy** [comment]
Thanks for the recommendations.

I was analyzing this during the weekend. For what I've seen, just reverting the commit you linked [(openjdk/jdk@3e904a)](https://github.com/openjdk/jdk/commit/3e904a4801b2bf2e988ba096e5cb64a17fd5fce7) will fix the bug.

For what I've seen, there are no tests in openjdk that validate or depend on this change. So, unless I add a specific test for this, reverting that commit is all that is needed to fix this.

My plan is then to fork openjdk, and send them a PR including just that reverted commit. I will then write a good description, explaining the issue in our case, and putting references and all. If they then ask me to open an issue, I'll do it.

**Comment by maurolacy** [comment]
FYI: [https://github.com/openjdk/jdk/pull/1697](https://github.com/openjdk/jdk/pull/1697).

**Comment by maurolacy** [comment]
Hi,

According to the latest comments in the [openjdk/jdk#1697](https://github.com/openjdk/jdk/pull/1697) thread, they are not going to change the behaviour of `ReleasePrimitiveArrayCritical` with `JNI_COMMIT` and `-Xcheck:jni`. It's still open if something will be changed with `Release*ArrayElements`.

That effectively means `commit()` is not only buggy, but also useless. So, I propose we remove `commit()` entirely, at least from `AutoPrimitiveArray`.

Once the issue with `Release*ArrayElements` is resolved, we can keep `commit()`, if it's not buggy / inconsistent. Or, remove it too from `AutoArray`.

What do you think?

**Comment by dmitry-timofeev** [comment]
Agree, commit in the critical variant is not particularly useful.

BTW, I've briefly sampled GH for some valid usages of JNI_COMMIT. [This OSS project](https://sourcegraph.com/github.com/tanis2000/minigame-rust@4707fbea5e6150653860e331c4921c1b0f17bc59/-/blob/android/Minigame/sdl/src/SDL/src/core/android/SDL_android.c#L744:23), for example, creates a _global reference_ to an array; then takes its "elements" (either a pointer to the original or a copy — it targets Android, where both are possible); and once in a while JNI_COMMITs them. I suppose, some code updates the "elements", commits them, and somehow notifies the Java part about the changes. This saves a potential copy from Java array.

Project Panama, I believe, has already brought a better way to access native memory than direct ByteBuffers (another option here), but I haven't checked that yet.
