### ISSUE TITLE
`JNIEnv::new_local_ref` has seemingly-unnecessary lifetime restriction

### ISSUE THREAD

**Issue by argv-minus-one** [jni-rs/jni-rs#301]
The JNI `NewLocalRef` function can be used to create a local reference from a global reference. [The spec specifically allows it](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#newlocalref), and I'm guessing that's its main purpose. However, the wrapper method `JNIEnv::new_local_ref` currently can't be used that way because it requires the provided `JObject` to have the same lifetime as the `JNIEnv` itself (which won't be the case for a `JObject` belonging to a `GlobalRef`). This restriction does not seem necessary and should probably be removed (that is, the type of `obj` should be changed from `JObject<'a>` to `JObject<'_>`).

Also, `JNIEnv::new_local_ref` has a type parameter `T` that doesn't seem to be used at all.

**Comment by dmitry-timofeev** [comment]
Can't `as_obj` be used to retrieve a JObject from the GlobalRef and pass it to `new_local_ref`? Agree that it must be possible to pass GlobalRefs to most JNI APIs. The docs on `new_local_ref` are not correct saying that the argument is _always_ a local ref.

**Comment by argv-minus-one** [comment]
No. I get a compile error because of the incorrect lifetime.

What I have is a cache of generated Java objects. Here's a generic version:

```rust
use jni::{
	errors::Result as JResult,
	JNIEnv,
	objects::{GlobalRef, JObject},
};
use std::{
	collections::{hash_map, HashMap},
	hash::Hash,
};

struct JCache<T> {
	refs: HashMap<T, GlobalRef>,
}

impl<T: Eq + Hash> JCache<T> {
	fn get<'e>(
		&mut self,
		env: JNIEnv<'e>,
		key: T,
		compute_jobject: impl FnOnce(JNIEnv<'e>, &T) -> JResult<JObject<'e>>,
	) -> JResult<JObject<'e>> {
		Ok(match self.refs.entry(key) {
			hash_map::Entry::Occupied(entry) => {
				let o: &GlobalRef = entry.get();
				let o = o.as_obj();
				let o: JObject<'e> = env.new_local_ref::<()>(o)?;
				o
			}
			hash_map::Entry::Vacant(entry) => {
				let o = compute_jobject(env, entry.key())?;
				entry.insert(env.new_global_ref(o)?);
				o
			}
		})
	}
}
```

This currently fails to compile:

```
error[E0623]: lifetime mismatch
  --> src/lib.rs:26:26
   |
17 |         &mut self,
   |         --------- these two types are declared with different lifetimes...
18 |         env: JNIEnv<'e>,
   |              ----------
...
26 |                 let o: JObject<'e> = env.new_local_ref::<()>(o)?;
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...but data from `self` flows into `env` here
```

If, however, the `new_local_ref` parameter's type is changed to `JObject<'_>`, then it compiles successfully.

My current workaround is to escape from lifetime constraints by turning the `JObject` into a raw pointer and then re-wrapping it with the correct lifetime:

```rust
let o = o.as_obj();
let o = JObject::<'e>::from(o.into_inner()); // workaround
let o: JObject<'e> = env.new_local_ref::<()>(o)?;
```

**Comment by maurolacy** [comment]
Can you send a PR with the proposed changes, so that we can evaluate it better?

**Comment by argv-minus-one** [comment]
OK. I've sent it as PR #319.
