### ISSUE TITLE
Does the static object created on the rust side get deallocated by the GC?

### ISSUE THREAD

**Issue by ammarmohammedva** [jni-rs/jni-rs#311]
Does the memory allocated for the static object (e.g. created using lazy_static) get deallocated by the GC if the program was closed expectedly/unexpectedly or should I do something to avoid the memory leak?

**Comment by stanislav-tkach** [comment]
All process memory will be "deallocated" when a process is terminated (either normally or abnormally), so no actions are required.

There is one catch though: for static types "destructors" (drops) aren't invoked, so if you have some other logic except freeing memory in the `Drop` trait implementation, then it wouldn't run automatically.

By the way, `once_cell` is more ergonomic than `lazy_static`.

**Comment by asmmo** [comment]
Thank you very much I have noticed that by profiling too.
