### ISSUE TITLE
How to log?

### ISSUE THREAD

**Issue by lattice0** [jni-rs/jni-rs#323]
```
#include <android/log.h>


__android_log_write(ANDROID_LOG_ERROR, "Tag", "Error here");//Or ANDROID_LOG_INFO, ...  

```

doing simple logging is unclear. I tried `log::info!` and it won't work. 

I'm lost on how to import a android function from a .h. How should it be done?

**Comment by stanislav-tkach** [comment]
Personally I don't have experience in developing for Android platform, but as far as I can see there are crates like `android_logger`.

**Comment by tkkcc** [comment]
use `android.util.Log` via jni

**Comment by rib** [comment]
Logging on Android can be handled using a crate such as [android_logger](https://crates.io/crates/android_logger)

E.g. add this to your deps:
`android_logger = "0.11.0"`

and initialize something like:
```rust
android_logger::init_once(android_logger::Config::default().with_min_level(log::Level::Info));
```

You don't need to use JNI to handle logging from Rust on Android.

Hope that helps!
