### ISSUE TITLE
class cannot be found

### ISSUE THREAD

**Issue by wojiaoyanxin** [jni-rs/jni-rs#326]
When the JNI method is called in the trust sub thread, an exception will be thrown if the class cannot be found

**Comment by TheDutchMC** [comment]
Need a little more detail than that I'm afraid.
- What class are you trying to create?
- Is the class loaded in Java?
- Show us your code
- Is the class in an external Java library, if so, what library?
- Is the class a nested class?

**Comment by rib** [comment]
Going to close this while there isn't enough information to understand the issue.
