### ISSUE TITLE
allocation free use

### ISSUE THREAD

**Issue by georgwi** [jni-rs/jni-rs#329]
First, thank you for providing this library, it works great!

In my application I need to call a rust library from Java which in turn calls methods on some Java objects. I also have a constraint that I cannot allocate during those calls. This is not possible currently, but I was able to avoid allocations by forking and making some changes here: https://github.com/georgwi/jni-rs/tree/allocation-free-use

I wanted to ask if you would be interested in a PR or implementing something similar for a future release? It seems to me that this might be a desirable feature for others. In addition, I wonder if this could improve performance (Issue #252 suggests a lot of time is spent in a vector allocation). I have not run a benchmark, but if you are interested I can and report back here.

Two elaborate on my changes a bit:
- [Mapping Args](https://github.com/georgwi/jni-rs/commit/757422246ea400cb2ba831d6633c6538ef91a366): calling a method (i.e. `env.call_method_unchecked(...)`) takes a slice of `JValue` and maps it to `jvalue`. In the process a vector is allocated. I changed the `call_method_unchecked` signature to accept a slice of `jvalue`. This could be made backwards compatible easily by adding another method such as `call_method_unchecked_noalloc`.
- [Object Return](https://github.com/georgwi/jni-rs/commit/61782d6ff3b37d892fd9bcc93e8a01876bc84d99): When calling a method that returns an object, a string with the returned class name (or really any content) has to be allocated for the argument `ret`: `JavaType::Object("hello world".into())`. In reality this string is never read. To avoid the string allocation I made an enum for `ReturnType` that serves a similar purpose as `JavaType` but it only contains the information needed. This could potentially be made backwards compatible by accepting a `ret` argument that can be converted to `ReturnValue` and implementing this conversion for `JavaType`.

Please let me know if you have any feedback and if you would like to pursue this further. I'd like to be able to depend on a release of this crate rather than a fork.

**Comment by stanislav-tkach** [comment]
I think that it is a useful change, but honestly speaking neither of current `jni-rs` maintainers are really active. Personally I'm checking issues and pull requests from time to time, but unfortunately I cannot promise a thorough review for a big pull request. Therefore proceed at your own risk. :upside_down_face:

**Comment by rib** [comment]
Closing this since #344 was merged.

Thanks for the original work here @georgwi!
