### ISSUE TITLE
Undefined behavior in release_string_utf_chars

### ISSUE THREAD

**Issue by dtolnay** [jni-rs/jni-rs#331]
The following safe program leads to release_string_utf_chars performing Undefined Behavior:

```rust
// [dependencies]
// jni = { version = "*", features = ["invocation"] }

fn main() {
    let init_args = jni::InitArgsBuilder::new().build().unwrap();
    let jvm = jni::JavaVM::new(init_args).unwrap();
    let jni_env = jvm.attach_current_thread().unwrap();
    let jstring = jni_env.new_string("...").unwrap();
    jni_env.release_string_utf_chars(jstring, 0xdeadbeefusize as _).unwrap();
}
```

```console
Segmentation fault (core dumped)
```

In general it is unsound for a safe API to result in UB.

**Comment by stanislav-tkach** [comment]
Thanks for pointing out this issue. You are definitely right: this function cannot enforce using only the result of the `get_string_utf_chars` function as an argument, so it should be marked as unsafe.
