### ISSUE TITLE
{get,set,take}_rust_field not compatible with Kotlin

### ISSUE THREAD

**Issue by MolotovCherry** [jni-rs/jni-rs#333]
Hi,

Due to the way Kotlin works internally, `get_rust_field`, `set_rust_field`, and `take_rust_field` are not always compatible.

Kotlin uses classes for storage of types rather than primitives, specifically `Long` in this case, and it converts to a primitive "if it can" (so won't always).

If you declare a non-nullable Kotlin field `private var foo: Long = 0`, then the bytecode generated will generate a Java primitive `J`, however, your functions expect to be able to check/set based on the field being `null` or not. In Kotlin, types are not nullable unless declared explicitly as such. So the correct way to declare the field would be `private var foo: Long? = null`. Unfortunately, due to what I mentioned before, this causes Kotlin's bytecode to generate the type as `Ljava/lang/Long;`, which means the code expecting type `J` no longer works.

The way to get and set the field in this case, for Kotlin specifically, would be
```rust
    let res = env.get_field(obj, "handle", "Ljava/lang/Long;").unwrap();
    // Ljava/lang/Long; object
    let ob = res.l().unwrap();
    // the primitive long is stored in the `value` field
    let value = env.get_field(ob, "value", "J").unwrap();
    println!("res {:?} ", value);
    // now we can just set this value field, and it'll be reflected back in Java
    env.set_field(ob, "value", "J", JValue::Long(1234)).unwrap();
```
As for setting it back to null (or checking for null), that's obvious since the type was nullable. Just set `obj` to null.

Note: It would be theoretically possible to set a field to null even though it wasn't marked as such in Kotlin. However, since kotlin won't allow null unless specified, the null check would still fail (since we had to fill it with a real value). Not withstanding the fact that the field would be null but the Kotlin typechecker wouldn't know anything about it (creating false positives - not a good idea)

**Comment by cherryleafroad** [comment]
For anyone else coming here that needs it for Kotlin.
Note: You'll need to modify it slightly to use the `env` function versions. I modified it with my own local functions to cache the outputs.

```rust
pub fn set_rust_field<R>(env: &JNIEnv, cls: &str, obj: &JObject, field: &str, rust_object: R) -> Result<()>
where
    R: Send + 'static
{
    let _ = env.lock_obj(*obj)?;

    // Check to see if we've already set this value. If it's not null, that
    // means that we're going to leak memory if it gets overwritten.
    let handle_field = get_field(env, cls, obj, field, "Ljava/lang/Long;")?.l()?;
    if !handle_field.is_null() {
        error!("cacher::set_rust_field:: field {} already set", field.to_owned());
        return Err(Box::new(jni::errors::Error::FieldAlreadySet(field.to_owned())));
    }

    let mbox = Box::new(::std::sync::Mutex::new(rust_object));
    let ptr: *mut Mutex<R> = Box::into_raw(mbox);

    let class = get_cls(env, "java/lang/Long")?;
    let jlong = env.new_object(class, "(J)V", &[(ptr as jni::sys::jlong).into()])?;

    set_field(env, cls, obj, field, "Ljava/lang/Long;", JValue::from(jlong))?;
    Ok(())
}

pub fn get_rust_field<R>(env: &JNIEnv, cls: &str, obj: &JObject, field: &str) -> Result<MutexGuard<'static, R>>
    where
        R: Send + 'static,
{
    let _ = env.lock_obj(*obj)?;

    let j_obj = get_field(env, cls, obj, field, "Ljava/lang/Long;")?.l()?;
    let ptr = get_field(env, "java/lang/Long", &j_obj, "value", "J")?.j()? as *mut Mutex<R>;

    if j_obj.is_null() {
        error!("cacher::get_rust_field:: field {} is null", field.to_owned());
        return Err(
            Box::new(CacherError::new(&*format!("field {} was null", field)))
        );
    }

    unsafe {
        // dereferencing is safe, because we checked it for null
        Ok((*ptr).lock().unwrap())
    }
}

pub fn take_rust_field<'a, R>(env: &JNIEnv, cls: &str, obj: &JObject, field: &str) -> Result<R>
    where
        R: Send + 'static,
{
    let mbox = {
        let _ = env.lock_obj(*obj)?;

        let j_obj = get_field(env, cls, obj, field, "Ljava/lang/Long;")?.l()?;
        let ptr = get_field(env, "java/lang/Long", &j_obj, "value", "J")?.j()? as *mut Mutex<R>;

        if ptr.is_null() {
            error!("cacher::take_rust_field:: field {} is null", field.to_owned());
            return Err(
                Box::new(CacherError::new(&*format!("field {} was null", field)))
            );
        }

        let mbox = unsafe { Box::from_raw(ptr) };

        // attempt to acquire the lock. This prevents us from consuming the
        // mutex if there's an outstanding lock. No one else will be able to
        // get a new one as long as we're in the guarded scope.
        drop(mbox.try_lock().unwrap());

        set_field(env, cls, obj, field, "Ljava/lang/Long;", JValue::from(::std::ptr::null_mut() as jobject))?;

        mbox
    };

    Ok(mbox.into_inner().unwrap())
}
```

**Comment by rib** [comment]
With the updated docs for `get/set/take_rust_field` (based on https://github.com/jni-rs/jni-rs/issues/336) and considering the discussion for #355 it's hopefully clearer now how they can be used with Kotlin so I'm going to close this for now. Please re-open if there are still unforeseen issues with using these with Kotlin.
