### ISSUE TITLE
Get existing JVM

### ISSUE THREAD

**Issue by majorsopa** [jni-rs/jni-rs#341]
How do you get a JavaVM or JNIEnv from an already-existing JVM?

**Comment by rib** [comment]
Are you on Android by any chance?

On Android then one recommended way would be to use the [ndk-context](https://crates.io/crates/ndk-context) crate.

There is also a standard `JNI_OnLoad` symbol that libraries can export to be given a jvm pointer when the library is loaded but this may not be an ideal solution if you don't have an obvious component you can make responsible for implementing that.

An example of that could like like this:
```
use std::{os::raw::c_void, panic::catch_unwind, sync::mpsc, thread, time::Duration};
use jni::{JNIEnv, JavaVM};
use jni::objects::{GlobalRef, JClass, JObject, JString};
use jni::sys::{jbyteArray, jint, jlong, jstring, JNI_VERSION_1_6};

#[allow(non_snake_case)]
#[no_mangle]
pub extern "system" fn JNI_OnLoad(vm: JavaVM, _: *mut c_void) -> jint {
    let env = vm.get_env().expect("Cannot get reference to the JNIEnv");
    JNI_VERSION_1_6
}
```

Hope that helps

**Comment by rib** [comment]
Hopefully the reply above helped answer this
