### ISSUE TITLE
Consider Cow<str> instead of String

### ISSUE THREAD

**Issue by MatrixDev** [jni-rs/jni-rs#342]
Consider following enum from the library:
```rust
pub enum JavaType {
   ...
    Object(String),
    ...
}
```

Most of the time object signature is known beforehand and can be stored in a `str + 'static`. It doesn't make sense to allocate a new string each time you want to create a `JavaType::Object`. It wouldn't be that bad if API was taking a shared references to `JavaType`, but it doesn't. Moreover signature is completely ignored when you call a jni method as only variant of the `JavaType` is required, not the actual signature.

It would be really nice to change this enum to:
```rust
pub enum JavaType {
   ...
    Object(Cow<'static, str>),
    ...
}
```

**Comment by rib** [comment]
This PR potentially addresses this too: https://github.com/jni-rs/jni-rs/pull/344

Originally proposed in issue https://github.com/jni-rs/jni-rs/issues/329 that branch adds a `ReturnType` that's a more limited `JavaType` enum that doesn't fully qualify the object type, and so it can avoid some of the redundant allocations that come from using `JavaType::Object`

**Comment by rib** [comment]
Just to add though; separate from the idea of having a separate `ReturnType` that doesn't need to keep any form of internal string, it does sound like something like this could still be good for the more general `JavaType`.

**Comment by rib** [comment]
I think it's hopefully reasonable to close this now that #344 has been merged which also addresses the same (underlying) issue here. (by adding a `ReturnType` that avoids the need for a `String` class path when specifying the return type.
