### ISSUE TITLE
How to handle enum types?

### ISSUE THREAD

**Issue by Fee0** [jni-rs/jni-rs#357]
I have an object like this which I want to return from a rust function:

```
class Stats
{
    public enum ReturnStatus { SUCCESS, WARNING, ERROR, UNKNOWN };
    public ReturnStatus status = ReturnStatus.UNKNOWN;
}
```

which methods do I need to use to set the `status` variable to an enum variant?

I created the object like this:

```
let stats_class = env.find_class("a/b/c/Stats").unwrap()
let stats = env.new_object(stats_class, "()V", &[]).unwrap();
```

**Comment by rib** [comment]
Hopefully the response from @TobiasDeBruijn is enough to answer this question @Fee0 so I'm going to close this issue now.

Please re-open if needed though.
