### ISSUE TITLE
Questions on memory ownership

### ISSUE THREAD

**Issue by krishnakumar4a4** [jni-rs/jni-rs#376]
We have started using JNI to interact with rust from android java layer. While we wrote some sample code, we have started to draw questions about responsibility of cleaning up memory, limitations and best practices. While I am able to get to a reasonable conclusion reading some material online. I would like confirm the same here.

### Scenario 1:
Passing java byte[] as an argument to rust function mapping to `jbyteArray` 

```rust
env.convert_byte_array(byte_array_from_java).unwrap()
```
This internally calls `GetByteArrayRegion` on JVM to copy the array from JVM memory to pre-allocated rust vector. I believe, once the rust function returns to java, the byte array on java side will be GC'ed by java while the vector on rust side will be dropped by Rust.

I also realised, convert_byte_array function doesn't need rust to release byte[] on JVM. I am assuming, JVM uses local ref to clean up the byte[] once the rust function returns (as I read from a stackoverflow [answer](https://stackoverflow.com/a/6245964))

### Scenario 2:
Passing string as an argument to rust function mapped to `JString`

```rust
env.get_string(string_from_java).expect("expected string");
```

This internally makes call to JNI `GetStringUTFChars` function which requires to call `ReleaseStringUTFChars` before returning to native function. Hence the returned type JavaStr has Drop trait implemented which calls `ReleaseStringUTFChars` when the rust function returns. In this case, releasing the string value allocated on JVM is released by rust layer.

### Scenario 3:
Returning `jbyteArray` to java layer which is mapped to java byte[] type

```rust
env.byte_array_from_slice(&rust_vector_of_bytes).unwrap()
```

This internally makes call to JNI functions `NewByteArray` to create array on JVM and `SetByteArrayRegion` to fill byte array from rust vector passed as argument. Both these functions do not require a release to be called on the rust side as the allocation happens on JVM. I think JVM takes care of GC'ing memory after the rust function returns. All we returned is a pointer (*mut _jobject) to the allocated byte array as a return value.

### Scenario 4:
Returning `jstring` to java layer which is mapped to java String type

I am assuming similar approach would be taken as point 3 (except the JNI function would be `NewStringUTF`)

### References:
- JNI functions doc from Oracle - https://docs.oracle.com/javase/6/docs/technotes/guides/jni/spec/functions.html#global_local

### P.S: It would be really great and helpful if someone can confirm my assumptions for above scenarios. Also, if you can, please add any unique scenario not listed above, limitations that you have come across, best practices etc. Thanks in Advance

**Comment by rib** [comment]
# Scenario 1
> This internally calls GetByteArrayRegion on JVM to copy the array from JVM memory to pre-allocated rust vector. I believe, once the rust function returns to java, the byte array on java side will be GC'ed by java while the vector on rust side will be dropped by Rust.

This doesn't sound quite right. This API conceptually has no affect on the lifetime of the Java-side array, besides requiring that it's a valid array object when it's called.

`convert_byte_array` copies data out of a Java array into a new Rust `Vec`. It doesn't return you any kind of local reference for the Java array and so you aren't really affecting the lifetime of the Java array - just reading from it.

For you to be able to safely call `convert_byte_array` then you would have to either have a local or global reference from somewhere for that array and if there is no other reference to the array then garbage collection for the Java array will be allowed (but not guaranteed) after those are released (but these references shouldn't be affected by calling `convert_byte_array`)

If the Rust function that calls `convert_byte_array` doesn't move that returned `Vec` outside of the stack frame for that function then it will be dropped as you say. Hypothetically the Rust function could for example move the `Vec` onto the heap, e.g. into an `Arc` whereby it might not be dropped depending on where the reference to that Arc might be sent.

**Comment by rib** [comment]
# Scenario 2

Your description here sounds correct yep.

For additional context you may be interested to review some of the recent `JavaStr` and `get_string` work that was done here:

https://github.com/jni-rs/jni-rs/pull/374 (added `into_raw` and `from_raw` APIs for `JavaStr` )

https://github.com/jni-rs/jni-rs/pull/372 (will remove the  very unsafe `env.get_string_utf_chars` and `env.release_string_utf_chars` functions for the next major release.)

https://github.com/jni-rs/jni-rs/pull/370  (Updated `get_string` to explicitly check it is passed a `java.lang.String` to avoid undefined behaviour + added `get_string_unchecked`)

It shouldn't generally matter but you may want to keep in mind that internally it's theoretically possible for `get_string` to return a reference to the storage for a `JString` without copying it (instead it may just pin it to ensure that it's not garbage collected). Practically it doesn't really make any difference though, something still needs to call to `ReleaseStringUTFChars` later which may either unpin the storage or it may free a copy of the storage. The C API for `GetStringUTFChars` exposes this implementation detail but the `jni-rs` Rust API doesn't currently expose that detail.

**Comment by rib** [comment]
# Scenario 3

I think your description here sounds right

`byte_array_from_slice` is going to create you a new Java array that's managed by the JVM and it's going to return you a local reference to your Rust code.

If the Rust function that call `byte_array_from_slice` was it's called from Java then when it returns to Java then the local references that Rust was holding will be released but the Java code itself will still have a reference to the new array. It then depends where that reference is passed in Java for determining when that array can potentially be garbage collected.

**Comment by rib** [comment]
# Scenario 4

Sounds about right. Essentially a `jstring` will be an object reference which may either be a local reference or a global reference to a `java.lang.String` Object. One typical way to get such a reference could be via `env.new_string` which will call `NewStringUTF` as mentioned - but really there may be lots of ways you might get ahold of an object reference to a string that you could return to Java.

If you haven't already reviewed / seen it - it could be good to check the JNI docs regarding local/global references here: https://docs.oracle.com/en/java/javase/12/docs/specs/jni/design.html#referencing-java-objects

Hope some of the notes above help.

**Comment by rib** [comment]
Hopefully the responses above clarify any of the questions you had

**Comment by krishnakumar4a4** [comment]
@rib Thanks for detailed responses, this makes clear sense. 

For beginners, I hope this thread gives pointers on how `jni-rs` and `Java JNI` play together on memory ownership or otherwise unavailable.
