### ISSUE TITLE
`JMethodID`/`JStaticMethodID` lifetime

### ISSUE THREAD

**Issue by stanislav-tkach** [jni-rs/jni-rs#38]
Both `JMethodID` and `JStaticMethodID` have lifetime associated with `JNIEnv`, but it isn't entirely correct:

> A field or method ID does not prevent the VM from unloading the class from which the ID has been derived. After the class is unloaded, the method or field ID becomes invalid. The native code, therefore, must make sure to:
> - keep a live reference to the underlying class, or
> - recompute the method or field ID

This way method id should depend on class and not on `JNIEnv`. As far as I can see, there is no easy way to express that in the Rust code. In my code I use "hack" to workaround current restriction:
```rust
struct CachedConstructor {
    pub element_class: GlobalRef,
    // `static` lifetime is used here.
    pub constructor_id: JMethodID<'static>,
}

impl<InnerIter> CachedConstructor {
    pub fn new(env: &JNIEnv, class_name: &str) -> Result<Self> {
        let class = env.find_class(class_name)?;
        let element_class = env.new_global_ref(class.into())?;
        let id = env.get_method_id(class_name, "<init>", "([B[B)V")?;
        Ok(CachedConstructor {
            element_class,
            // Transmute & unsafe:
            constructor_id: unsafe { mem::transmute(id) },
        })
    }
}
```

Any advices on how to handle it better?

**Comment by jechas01** [comment]
This is only a problem when you want to make the method/field id outlive the method it's obtained from, correct? It shouldn't be able to escape the extern method that where it first gets looked up, since the JNIEnv can't either. We might need something like you've got above in order to give out "Global" Method/FieldIDs.

**Comment by koutheir** [comment]
> This is only a problem when you want to make the method/field id outlive the method it's obtained from, correct?

Correct.

> It shouldn't be able to escape the extern method that where it first gets looked up, since the JNIEnv can't either.

Actually, it can. The `JNIEnv` object obtained by a JNI function can be kept in thread-local storage, and it can be used as long as that thread is attached to the JVM. That thread can also cache identifiers of methods and fields.

**Comment by cherryleafroad** [comment]
Is there a better way to cache these rather than having to use `std::mem::transmute()`? At the very least classes are cacheable without an issue by using `new_global_ref`, but I kinda feel hacky having to `std::mem::transmute()` on these ones
