### ISSUE TITLE
Add convenience method for calling `DetroyJavaVM`

### ISSUE THREAD

**Issue by keastrid** [jni-rs/jni-rs#391]
This is fairly simple to workaround, but having a convenient way to call it would be nice.

[Calling this method unloads the JVM](https://docs.oracle.com/en/java/javase/17/docs/specs/jni/invocation.html#unloading-the-vm), and functionally it is also important for GUI applications using AWT/Swing in that it waits for the application to finish before terminating. Without this call, such applications immediately shutdown after opening the main window.

**Comment by rib** [comment]
Yeah this sort of seems like it should be done within a `Drop` implementation but even though `JavaVM` may load the vm via 
`JavaVM::new()` or `JavaVM::with_libjvm()` it's conceptually just a transparent pointer that doesn't really own anything.

(It's e.g. possible to create any number of `JavaVM`s via JNIEnv::get_java_vm`)

I guess the simplest (`unsafe`) approach could just be to directly expose an api like `JavaVM::destroy()` which would be very non-Rusty and it would just need to be documented that any attempt to access the vm afterwards would likely result in a crash.

Maybe it would be better if all the `invocation` functionality for loading a vm were actually moved out into some kind of `OwnedJavaVM` which could then implement `Drop`. There would still be the danger of something holding on to a `JavaVM` pointer though that would be an invalid pointer after the `OwnedJavaVM` gets dropped.

**Comment by keastrid** [comment]
An `OwnedJavaVM` automatically handling this would be good, but even just a `JavaVM::destroy()` would be good.

**Comment by rib** [comment]
Okey, I've taken a look at adding a `JavaVM::destroy()` method as discussed here.

Please see: https://github.com/jni-rs/jni-rs/pull/406

There are some significant safety issues related to the use of daemon threads that I've tried to describe in the `# Safety` section of the API, but with this addition it would at least be possible to try and unload a jvm if you're feeling lucky :-)
