### ISSUE TITLE
Reconsider keeping `GlobalRef::as_obj()` for now since `.as_ref()` can be ambiguous

### ISSUE THREAD

**Issue by rib** [jni-rs/jni-rs#408]
As part of https://github.com/jni-rs/jni-rs/pull/398 we decided to mark `GlobalRef::as_obj()` as deprecated since it's now possible to get a reference to a `JObject` via the `AsRef<JObject>` implementation but a few times already since landing that PR I've found that using `.as_ref()` leads to the compiler complaining that it it's underspecified since there are multiple `AsRef` implementations for `GlobalRef`.

It make sense that we implement `AsRef<JObject>` for a `GlobalRef` so it can be seamlessly passed to APIs that need an object reference and there's no ambiguity in those cases where an argument is specifically constrained to `impl AsRef<JObject>`. At other times though you just want to cast a `GlobalRef` to a `JObject` reference but there might not be enough context for the compiler to know which implementation of `.as_ref()` you're trying to use.

@argv-minus-one ping ^ (any objection to me creating a patch to remove the deprecation for `.as_obj()` for now?)

I can imagine this will also be revisited later if we look at making `GlobalRef` generic so it doesn't erase the type of object it wraps.

**Comment by argv-minus-one** [comment]
No objections here. :+1:
