### ISSUE TITLE
What does the correct class descriptor format looks like for `find_class`?

### ISSUE THREAD

**Issue by ChAoSUnItY** [jni-rs/jni-rs#418]
As far as I know about JVM, there are 3 different representation of a class name, which are canonical name, internal name, and descriptor. But when I tried to use `find_class` to find a class with string `Ljava/lang/String;`, JNI said:
```
WARNING in native method: JNI FindClass received a bad class descriptor "Ljava/lang/String;".  A correct class descriptor has no leading "L" or trailing ";".  Incorrect descriptors will not be accepted in future releases.
```
Isn't object class' descriptor in JVM bytecode always prefixed with `L` and suffixed with `;`?

**Comment by argv-minus-one** [comment]
No. That's a *type descriptor*, which can describe either a class type like `java.lang.String` *or* a primitive type like `int`. The `L` means that this type is a class type, and the class descriptor (the fully-qualified, slash-separated name of the class) comes between the `L` and the `;`. Primitive types are indicated with other letters, like `I` for `int`.

`find_class`, however, doesn't look up primitive types; it *only* looks up classes. It expects just the *class descriptor*, `java/lang/String`. The same is true in other places where only a class is permitted, like `new_object` and `call_static_method`.

See the documentation for [the C JNI function `FindClass`](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#findclass).

Note that there is one exception to all of this: arrays. Per the documentation linked above, `[Ljava/lang/String;` *is* permitted for `FindClass`/`find_class`, even though `Ljava/lang/String;` is not.

**Comment by ChAoSUnItY** [comment]
Thanks for your reply, that's really helpful since there's handful of JNI related info on internet.
