### ISSUE TITLE
how to get java list on rust

### ISSUE THREAD

**Issue by popeye2022** [jni-rs/jni-rs#444]
`     let elem = env.get_object_array_element(&_list_params, i).expect("msg");
       let witness_object = env.get_field(&elem, "name", "J").expect("witness field not found");
`
java will crash ,this is error log

Internal exceptions (2 events):
Event: 0.201 Thread 0x00007fae26809000 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x000000076ab07ce0) thrown at [/System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x64/jdk8u361/
Event: 0.201 Thread 0x00007fae26809000 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x000000076ab07fc8) thrown at [/System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x64/jdk8u361/3183/hotspot/src/s

**Comment by argv-minus-one** [comment]
If `_list_params` is a reference to a `java.util.List` rather than a Java array, then yes, this is incorrect. Use [`jni::objects::JList`](https://docs.rs/jni/latest/jni/objects/struct.JList.html) to access the contents of a `java.util.List`.

**Comment by rib** [comment]
Going to close this, while guessing that `get_object_array_element` wasn't being passed a `JObjectArray` - judging by the name of the variable and exception.

I guess this may have also been tested with a version of jni -rs before #400 landed which improved the type safety of this API.

Please re-open if can provide more details.
