### ISSUE TITLE
Question: How I use `GetObjectRefType`

### ISSUE THREAD

**Issue by Rabbit0w0** [jni-rs/jni-rs#449]
In C++, I have a code snippet:
```cpp
if (env->GetObjectRefType(ref) == JNILocalRefType) env->DeleteLocalRef(ref);
```
But I found no corresponding method to do this is Rust.

**Comment by rib** [comment]
It looks like jni-rs is currently missing null checks before calling delete_local_ref and delete_global_ref (the spec doesn't seem to clarify if it's OK to pass null to these, though I guess they are just noops as you'd want).

Null is a special case though, and I think it's probably good that you can make a null GlobalRef or null AutoLocal.

You shouldn't have to worry about whether references are valid or not unless dealing with raw sys types with unsafe code.

**Comment by Rabbit0w0** [comment]
Oh okay, thanks.

**Comment by xanahopper** [comment]
Consider a scenario: when a JNI method returns a `GlobalRef` that is also held by Rust, and Java passes it again as a parameter to a JNI method, we are unable to determine whether this parameter is a `GlobalRef`. Additionally, we cannot create (or restore) a GlobalRef except through the `new_global_ref` method which create a new global ref actually even jobject is already global ref.
