### ISSUE TITLE
Make methods `const fn` when it makes sense

### ISSUE THREAD

**Issue by koutheir** [jni-rs/jni-rs#451]
Some methods (*e.g.,* [`JObject::from_raw()`](https://docs.rs/jni/latest/jni/objects/struct.JObject.html#method.from_raw)) can become `const fn`s, allowing their usage in constant contexts, such as defining a constant `null` `JObject`.

Does it make sense to open a pull request for this? Or is this transformation undesirable in this project?

**Comment by rib** [comment]
`const fn` sounds good for `JObject::null()`.

I'm not entirely sure what the use case for `from_raw()` would be in a constant context - since the only type of reference that's going to be valid in a const context would surely by `JObject::null()`?
