### ISSUE TITLE
The performance seems to be only 80% of that of cpp (jni)

### ISSUE THREAD

**Issue by redoriental** [jni-rs/jni-rs#471]
Please clarify if this project is a rewrite of JNI or if it acts as an intermediary with C++.

**Comment by knopp** [comment]
This project is a Rust wrapper around C JNI API. How exactly did you determine that the performance is "80% of cpp"?

**Comment by rib** [comment]
Closing this since the question was answered by @knopp and the performance assertion is lacking details.

Please reopen with more details if there is a more specific performance problem that can be reproduced.
