### ISSUE TITLE
Possibility of creating InitArgsBuilder's arguments in runtime

### ISSUE THREAD

**Issue by r3bb1t** [jni-rs/jni-rs#481]
I can't find a way to supply the needed amount of arguments to the InitArgsBuilder in runtime, all i see is that the exact amount of arguments must be known during compile time. I don't want to hardcode all the options and be able to provide arguments via config file in runtime.

Currently i am creating **JVM** instance like that:

```rust
  let jvm_args = prepare_jvm_args!("-Xcheck:jni");
  let jvm = Box::new(JavaVM::new(jvm_args).unwrap());
```

where **prepare_jvm_args** macro has the following source code:

```rust
  #[macro_export]
  macro_rules! prepare_jvm_args {
      ( $( $x:expr ),* ) => {
          {
              jni::InitArgsBuilder::new()
                  .version(jni::JNIVersion::V8)
                  $(
                      .option($x)
                  )*
                  .build()
                  .unwrap()


          }
      };
  }
```

I think that it would be nice to add method named something like **option_vec** for **InitArgsBuilder** struct where we can supply the vector of Strings.

P.s. I also noticed that **JVM** allocated the heap (**Box**) works faster than the regular stack-allocated **JVM**.

**Comment by argv-minus-one** [comment]
Try this:

```rust
let mut builder =
    jni::InitArgsBuilder::new()
    .version(jni::JNIVersion::V8);

$(
    builder = builder.option($x);
)*

builder.build().unwrap()
```

>P.s. I also noticed that JVM allocated the heap (Box) works faster than the regular stack-allocated JVM.

That's very strange. The `JavaVM` structure contains only a single pointer. Boxing it should be significantly slower.

**Comment by r3bb1t** [comment]
Thanks, your example actually helped. I created a function and named it **prepare_jvm_args_runtime** which looks like this:

```rust
fn prepare_jvm_args_runtime(jvm_args: &Vec<String>) -> InitArgs {
    let mut builder = jni::InitArgsBuilder::new().version(jni::JNIVersion::V8);
    for arg in jvm_args {
        builder = builder.option(arg);
    }
    builder.build().unwrap()
}
```

I'm not sure if i can make it look prettier, but it is not much important right now.
