### ISSUE TITLE
JavaVM should be Clone

### ISSUE THREAD

**Issue by jrose-signal** [jni-rs/jni-rs#503]
JavaVM wraps a virtual dispatch table that's assumed to have `'static` lifetime, and exposes `from_raw` and `get_java_vm_pointer`, with no Drop glue. It should implement Clone, since there is no cost to doing so.

Note that JavaVM could even implement *Copy,* but it could reasonably be argued that that might prevent a future improvements to JavaVM.

**Comment by argv-minus-one** [comment]
That's planned in #478.
