### ISSUE TITLE
How to pass JavaVM from c to rust

### ISSUE THREAD

**Issue by qwq233** [jni-rs/jni-rs#514]
How to pass JavaVM from c to rust

I want to call a function that is in my rust project from my c project.

The function that calls this function in rust is JNI_OnLoad

I have tried passing JavaVM parameter like this but it crashed

C side
```c
jint JNI_OnLoad (JavaVM *vm, void *reserved) {
   // do sth
    function(vm);
   // ...
}
```

Rust side
```rust
#[no_mangle]
pub unsafe extern "C" fn function(ptr: *mut sys::JavaVM) -> bool {
    let env = JavaVM::from_raw(ptr);
    let env = match env {
        Ok(env) => env,
        Err(e) => {
            log::e("librs".to_string(), format!("env: {}", e));
            return false;
        }
    };
    let env = env.get_env(); // crashed here
    let mut env = match env {
        Ok(env) => env,
        Err(e) => {
            log::e("librs".to_string(), format!("env: {}", e));
            return false;
        }
    };
    // do sth
}
```

**Comment by argv-minus-one** [comment]
That looks correct.

I hacked together [an example based on your code](https://github.com/jni-rs/jni-rs/files/13698639/c-jni-interop.zip), and it seems to work fine. I tried it on Debian Linux Sid x86_64 with Java 17.0.9-ea, Clang 16.0.6, and Rust 1.71.1.

So, I'm not sure why it's crashing for you. Can you give some details about your platform, and prepare a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of the problem you're having?

---

To run my example:

1. Get a Linux machine with Rust and Clang installed.
1. Unzip this archive on that machine.
2. `cd c-jni-interop && sh ./run.sh`

If successful, it will print the usual Cargo compilation messages, then `Successfully got JNIEnv` (printed from the Rust function `function`), then `Hello, world!` (printed by Java code calling into C, after successfully loading the native library).

Note: the code in this example is platform-agnostic, but the `run.sh` script assumes Linux, and will need to be adjusted for other platforms.

**Comment by qwq233** [comment]
uh that's weird.
I clean the cache and recompile it and suddenly it works.
It was running on a Android device actually so maybe there was something wrong with ndk or gradle stuff.
Thanks for answering anyway
