### ISSUE TITLE
Unsound usages of unsafe implementation from small size to large size

### ISSUE THREAD

**Issue by llooFlashooll** [jni-rs/jni-rs#536]
Hi, I am scanning the jni in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/wrapper/objects/jvalue.rs:198:13: 198:49
``` rust
pub fn as_jni(&self) -> jvalue {
    let val: jvalue = match self {
        Self::Object(obj) => jvalue { l: obj.as_raw() },
        Self::Byte(byte) => jvalue { b: *byte },
        Self::Char(char) => jvalue { c: *char },
        Self::Short(short) => jvalue { s: *short },
        Self::Int(int) => jvalue { i: *int },
        Self::Long(long) => jvalue { j: *long },
        Self::Bool(boolean) => jvalue { b: *boolean as i8 },
        Self::Float(float) => jvalue { f: *float },
        Self::Double(double) => jvalue { d: *double },
        Self::Void => jvalue {
            l: ::std::ptr::null_mut(),
        },
    };
    trace!(\"converted {:?} to jvalue {:?}\", self, unsafe {
        ::std::mem::transmute::<_, u64>(val)
    });
    val
}
```

This unsound implementation would create a misalignment issues. If the smaller size is converted to a larger size, it would potentially lead to access out-of-bound in the memory.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by argv-minus-one** [comment]
I don't see an alignment problem here. Please explain.

I see three things happening in this function:

1. Writing a value into a `repr(C)` `union` field. I'm not aware of any special alignment-related considerations when doing this.
2. Transmuting that `union` type into `u64`, for display. [The documentation](https://doc.rust-lang.org/stable/std/mem/fn.transmute.html) specifically says there are no alignment-related considerations when doing this unless the result is a pointer, which in this case it is not.
3. Returning what appears to be a well-formed `jvalue`.
