### ISSUE TITLE
how to cache jclass

### ISSUE THREAD

**Issue by HollisMeynell** [jni-rs/jni-rs#549]
I'm new to Rust, so my code might not be very idiomatic. I want to know how to correctly obtain a global reference to a jclass cache.

this piece of code works without any panic.
```
let env:&mut env; //< from function field

let class = env.find_class("package/class")?;
let global = env.new_global_ref(class)?;
let j_class = global.as_raw() as jclass;
let class = unsafe { JClass::from_raw(j_class) };
env.get_method_id(class, "name", "()V"); //  <====== working here is very normal.
```

but this will panic, 
```
let class = some_cache("ClassName", || {
        let class = env.find_class("package/class")?;
        let global = env.new_global_ref(class)?;
        Ok(global.as_raw() as jclass)
})?;
let class = unsafe { JClass::from_raw(class) };
env.get_method_id(class, "name", "()V"); //  <====== now, it panic here.
```
`some_cache()` implment mod:
```
use jni::objects::{JClass, JFieldID, JMethodID, JStaticFieldID, JStaticMethodID};
use jni::sys::{jboolean, jclass, jfieldID, jmethodID, JNI_TRUE};
use jni::JNIEnv;
use std::collections::HashMap;
use std::sync::atomic::AtomicI64;
use std::sync::atomic::Ordering::SeqCst;
use std::sync::Once;

type JniIdMap = HashMap<&'static str, usize>;
static GLOBAL_JNI_ID: AtomicI64 = AtomicI64::new(0);
static INIT: Once = Once::new();

fn get_global_map() -> Result<&'static mut JniIdMap> {
    INIT.call_once(|| {
        let map: JniIdMap = JniIdMap::new();
        let m_ptr = Box::into_raw(Box::new(map)) as i64;
        unsafe {
            GLOBAL_JNI_ID.store(m_ptr, SeqCst);
        }
    });

    let point = unsafe { GLOBAL_JNI_ID.load(SeqCst) } as *mut JniIdMap;
    let map = unsafe {
        point
            .as_mut()
            .unwrap()
    };
    Ok(map)
}
fn get_cache(key: &str) -> Option<usize> {
    let map = get_global_map().unwrap();
    map.get(key).map(|i| *i)
}

fn set_cache(key: &'static str, ptr: usize) -> Result<()> {
    let map = get_global_map()?;
    map.insert(key, ptr);
    Ok(())
}
fn some_cache(key: &'static str, default:impl FnOnce() -> Result<jclass>) -> Result<jclass> {
    let j = match get_cache(key) {
        None => {
            println!("is null");
            let j_class = default()?;
            set_cache(key, j_class as usize)?;
            j_class
        }
        Some(ptr) => ptr as jclass,
    };
    Ok(j)
}
```

**Comment by argv-minus-one** [comment]
What's the panic message? From what I can see, this should work as long as the cache is only ever used from a single thread.

It will definitely misbehave if you access the cache from multiple threads, though. Your cache implementation has a data race: although the pointer to the `HashMap` is kept in atomic storage, there's no synchronization of the `HashMap`'s contents. I recommend you store the `GlobalRef`s using a caching library like [moka](https://crates.io/crates/moka), or a concurrent map library like [dashmap](https://crates.io/crates/dashmap), instead.

Also, you're storing a pointer to the cache itself in the global variable `GLOBAL_JNI_ID`. Use [`std::sync::LazyLock`](https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html) instead; it does basically the same thing, but correctly (you're using `AtomicI64` instead of `AtomicPtr`) and more efficiently (`LazyLock` won't allocate a `Box` for its contents). If you can't use Rust 1.80 or later, use [`sync::Lazy`](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html) from the [`once_cell`](https://crates.io/crates/once_cell) library; it does the same thing as `LazyLock`.

**Comment by HollisMeynell** [comment]
> What's the panic message? From what I can see, this should work as long as the cache is only ever used from a single thread.
> 
> It will definitely misbehave if you access the cache from multiple threads, though. Your cache implementation has a data race: although the pointer to the `HashMap` is kept in atomic storage, there's no synchronization of the `HashMap`'s contents. I recommend you store the `GlobalRef`s using a caching library like [moka](https://crates.io/crates/moka), or a concurrent map library like [dashmap](https://crates.io/crates/dashmap), instead.
> 
> Also, you're storing a pointer to the cache itself in the global variable `GLOBAL_JNI_ID`. Use [`std::sync::LazyLock`](https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html) instead; it does basically the same thing, but correctly (you're using `AtomicI64` instead of `AtomicPtr`) and more efficiently (`LazyLock` won't allocate a `Box` for its contents). If you can't use Rust 1.80 or later, use [`sync::Lazy`](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html) from the [`once_cell`](https://crates.io/crates/once_cell) library; it does the same thing as `LazyLock`.

if i use cache `jclass` to  `find method_id`
```
Stack: [0x0000777524b07000,0x0000777524c07000],  sp=0x0000777524c04b48,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xcb5053]  oopDesc::metadata_field(int) const+0x3
V  [libjvm.so+0x9841f7]  jni_GetStaticMethodID+0xa7
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
```

**Comment by argv-minus-one** [comment]
That's part of a JVM crash message, not a Rust panic message. Also, it doesn't look like you pasted the entire message, so I can't see what the actual problem is. Please paste the whole thing.

**Comment by HollisMeynell** [comment]
cache code, [cache](https://github.com/HollisMeynell/osu-framework/blob/309f145423d71c5e142db3cd4744740861a9da2e/spring-osu-extended/native/src/java.rs#L82) , [use](https://github.com/HollisMeynell/osu-framework/blob/309f145423d71c5e142db3cd4744740861a9da2e/spring-osu-extended/native/src/osu/difficulty.rs#L142), and [kotlin class](https://github.com/HollisMeynell/osu-framework/blob/309f145423d71c5e142db3cd4744740861a9da2e/spring-osu-extended/src/main/kotlin/rosu/JniDifficultyAttributes.kt#L14), 


the short code:
```
static GLOBAL_CACHE: LazyLock<Cache<u32, usize>> = LazyLock::new(|| Cache::new(50));

fn get_id(key: u32) -> Option<usize> {
    GLOBAL_CACHE.get(&key)
}

fn set_id(key: u32, ptr: usize) -> Result<()> {
    GLOBAL_CACHE.insert(key, ptr);
    Ok(())
}

pub fn get_jni_class(key: u32, default: impl FnOnce() -> Result<jclass>) -> Result<jclass> {
    let j = match get_id(key) {
        None => {
            let raw = default()?;
            set_id(key, raw as usize)?;
            raw
        }
        Some(p) => p as jclass,
    };
    Ok(j)
}

#[jni_fn("class")]
fn test(env: &mut JNIEnv, this: &JObject) {
    let jclass = get_jni_class(PERFORMANCE_ATTR_CLASS, || {
        let class = env.find_class("org/spring/osu/extended/rosu/JniPerformanceAttributes")?;
        let class = env.new_global_ref(class)?;
        Ok(class.as_raw() as jclass)
    })?;

    let method = get_jni_static_method_id(PERFORMANCE_ATTR_MANAI, || {
        let class = unsafe { JClass::from_raw(jclass) };
        let field = env.get_static_method_id(
            class,
            "createMania",
            "(DDLorg/spring/osu/extended/rosu/ManiaDifficultyAttributes;)Lorg/spring/osu/extended/rosu/JniPerformanceAttributes;",
        )?;
        Ok(field)
    })?;
}
```

log file
[hs_err_pid93254.log](https://github.com/user-attachments/files/17891797/hs_err_pid93254.log)

**Comment by HollisMeynell** [comment]
> That's part of a JVM crash message, not a Rust panic message. Also, it doesn't look like you pasted the entire message, so I can't see what the actual problem is. Please paste the whole thing.

Sorry, maybe I expressed it wrongly. It should not cause rust panic but jvm crash, how should I fix it? I can provide reproducible .so and jar packages, or anything I can do.

**Comment by argv-minus-one** [comment]
See where you do `class.as_raw() as jclass`? This drops the `GlobalRef`, causing the global reference to be deleted, as soon as the closure returns. Since the global reference is already deleted, the program crashes when you try to use it.

You need to store the `GlobalRef`, not the `jclass`, in the cache.

Also, you can go from `&GlobalRef` to `&JClass` without using raw pointers or `unsafe` at all. If you have a variable `global_ref: &GlobalRef`, then `<&JClass>::from(global_ref.as_obj())` will evaluate to `&JClass`. So, you'd rewrite `fn test` like so:

```rust
#[jni_fn("class")]
fn test(env: &mut JNIEnv, this: &JObject) {
    let jclass = get_jni_class(PERFORMANCE_ATTR_CLASS, || {
        let class = env.find_class("org/spring/osu/extended/rosu/JniPerformanceAttributes")?;
        let class = env.new_global_ref(class)?;
        Ok(class)
    })?;

    let method = get_jni_static_method_id(PERFORMANCE_ATTR_MANAI, || {
        let class = <&JClass>::from(jclass.as_obj());
        let field = env.get_static_method_id(
            class,
            "createMania",
            "(DDLorg/spring/osu/extended/rosu/ManiaDifficultyAttributes;)Lorg/spring/osu/extended/rosu/JniPerformanceAttributes;",
        )?;
        Ok(field)
    })?;
}
```
