### ISSUE TITLE
Get static field

### ISSUE THREAD

**Issue by fpoli** [jni-rs/jni-rs#57]
Is there a way to access a static field?

**Comment by jechase** [comment]
Unless there are wrapper methods for the JNI GetStaticField* methods, I don't think so. I'd need to do a bit more research on how they're represented in the JNI API to determine how much work it would be to add support for them.

**Comment by dmitry-timofeev** [comment]
@fpoli 
I believe you've already discovered the approach to access a static field. I've added a test/example in #117 for future reference.

**Comment by fpoli** [comment]
Thank you for the example! In the end I used a static getter, but this way is much nicer
