### ISSUE TITLE
How can I use 'registerNatives' to register native methods?

### ISSUE THREAD

**Issue by seventh7me** [jni-rs/jni-rs#92]
Hi guys,
  How can I use 'registerNatives' to register native methods dynamically (using jni-rs)?

**Comment by dmitry-timofeev** [comment]
Done in #214

**Comment by tisonkun** [comment]
@dmitry-timofeev Any code demo to use register_native_methods?

**Comment by dmitry-timofeev** [comment]
@tisonkun I am afraid not — #214 is all we've got. If you figure that out and come up with a good example — please consider extending it.
